# https://github.com/prometheus-operator/prometheus-operator/blob/main/example/user-guides/alerting/alertmanager-example-service.yaml
# https://prometheus-operator.dev/docs/platform/platform-guide/#exposing-the-alertmanager-service
# We don't use a node port, we use an ingress
{{- if eq .Values.kube_x.prometheus.alertmanager.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
{{- end -}}
