{{- if eq .Values.kube_x.prometheus.node_exporter.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  ports:
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP
{{- end }}