{{/*
  Grafana Instance (Cloud or Cluster)

  Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'kube_x.grafana.instance.target=cloud'  \
    --set 'kube_x.grafana.instance.cloud.apiToken=xxxx'  \
    --set 'kube_x.grafana.instance.cloud.stackName=xxxx'  \
    . | yq

*/}}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
{{/*
Create a cloud instance
https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/grafana-operator/manage-dashboards-argocd/
*/}}
{{- if eq ( ((.Values.kube_x).grafana).instance.target) "cloud" -}}
metadata:
  name: {{ .Values.kube_x.grafana.instance.cloud.stackName }}
  namespace: '{{.Release.Namespace}}'
  labels:
    dashboards: {{ required "kube_x.grafana.cloud.stackName is required" .Values.kube_x.grafana.instance.cloud.stackName }}
spec:
  external:
    url: https://{{ .Values.kube_x.grafana.instance.cloud.stackName }}.grafana.net/
    apiKey:
      name: '{{ template "grafana-cloud-secret-name" . }}'
      key: '{{ template "grafana-cloud-secret-key" . }}'
{{- end -}}
{{/*
  Create a cluster local instance
  https://grafana.github.io/grafana-operator/docs/quick-start/#creating-a-grafana-instance

  Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'kube_x.grafana.instance.target=cluster'  \
    --set 'kube_x.cluster.adminUser.username=xxxx'  \
    --set 'kube_x.cluster.adminUser.password=xxxx'  \
    . | yq
*/}}
{{- if eq ( ((.Values.kube_x).grafana).instance.target) "cluster" -}}
metadata:
  namespace: '{{.Release.Namespace}}'
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    security:
      admin_user: {{ required "kube_x.cluster.adminUser.username is required for a local grafana instance" .Values.kube_x.cluster.adminUser.username }}
      admin_password: {{ required "kube_x.cluster.adminUser.password is required for a local grafana instance" .Values.kube_x.cluster.adminUser.password }}
{{- end -}}