{{/*
  Grafana Instance (Cloud or Cluster)
  See CRD doc:   https://grafana.github.io/grafana-operator/docs/grafana/

  Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'kube_x.grafana.instance.target=cloud'  \
    --set 'kube_x.grafana.instance.cloud.apiToken=xxxx'  \
    --set 'kube_x.grafana.instance.cloud.stackName=xxxx'  \
    . | yq

*/}}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.kube_x.grafana.instance.label }}
  namespace: '{{.Release.Namespace}}'
  labels:
    {{/*
      Label used to apply Grafana CRD to this instance (ie which Grafana instance a CRD dashboard, ... resource applies to)
      https://grafana.github.io/grafana-operator/docs/overview/#instanceselector
    */}}
    dashboards: {{ required "kube_x.grafana.instance.label is required" .Values.kube_x.grafana.instance.label }}
spec:
{{/*
Create a cloud instance (external)
https://grafana.github.io/grafana-operator/docs/grafana/#external-grafana-instances
https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/grafana-operator/manage-dashboards-argocd/
*/}}
{{- if eq ( ((.Values.kube_x).grafana).instance.target) "cloud" -}}
  external:
    url: https://{{ .Values.kube_x.grafana.instance.label }}.grafana.net/
    apiKey:
      name: '{{ template "grafana-cloud-secret-name" . }}'
      key: '{{ template "grafana-cloud-secret-key" . }}'
{{- end -}}
{{/*
  Create a cluster local instance
  https://grafana.github.io/grafana-operator/docs/quick-start/#creating-a-grafana-instance

  Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'kube_x.grafana.instance.target=cluster'  \
    --set 'kube_x.grafana.instance.hostname=grafana.bar.com'  \
    --set 'kube_x.cluster.adminUser.username=xxxx'  \
    --set 'kube_x.cluster.adminUser.password=xxxx'  \
    . | yq
*/}}
{{- if eq ( ((.Values.kube_x).grafana).instance.target) "cluster" -}}
  {{/*
    Ingress is defined as Yaml values.
    https://grafana.github.io/grafana-operator/docs/examples/ingress_https/readme/
    Nonte: it seems that they use the Helm Chart ???
    https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml
   */}}
  {{- if ne ( ((.Values.kube_x).grafana).instance.hostname) "" -}}
  ingress:
    metadata:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
        cert-manager.io/cluster-issuer: '{{ .Values.kube_x.cert_manager.defaultIssuerName }}'
        {{- end }}
    spec:
      ingressClassName: traefik
      rules:
        - host: '{{ .Values.kube_x.grafana.instance.hostname }}'
          http:
            paths:
              - backend:
                  service:
                    name: '{{ .Values.kube_x.grafana.instance.label }}-service'
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
      tls:
        - hosts:
            - '{{ .Values.kube_x.grafana.instance.hostname }}'
          secretName: '{{ include "grafana-name" . }}'
      {{- end }}
  {{- end -}}
  {{/*
      Config Doc
      https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
  */}}
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: {{ required "kube_x.cluster.adminUser.username is required for a local grafana instance" .Values.kube_x.cluster.adminUser.username }}
      admin_password: {{ required "kube_x.cluster.adminUser.password is required for a local grafana instance" .Values.kube_x.cluster.adminUser.password }}
      admin_email: {{ required "kube_x.cluster.adminUser.email is required for a local grafana instance" .Values.kube_x.cluster.adminUser.email }}
{{- end -}}