{{- if ne .Values.kubee.gogs.hostname "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gogs
  namespace: {{ .Values.kubee.gogs.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if ne (((.Values).kubee).cert_manager).enabled false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kubee.cert_manager.defaultIssuerName }}'
    {{- end }}
spec:
  rules:
    - host: {{ .Values.kubee.gogs.hostname }}
      http:
        paths:
          - backend:
              service:
                name: gogs
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.kubee.gogs.hostname }}
      secretName: gogs-cert
{{- end -}}
