apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
  labels:
    app.kubernetes.io/name: gogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M # was 69M