# A self-signed issuer, used to create the dex CA private key and cert (see below Certificate)
{{/* https://cert-manager.io/docs/usage/istio-csr/installation/ */}}
{{/* https://raw.githubusercontent.com/cert-manager/website/7f5b2be9dd67831574b9bde2407bed4a920b691c/content/docs/tutorials/istio-csr/example/example-issuer.yaml */}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubee-name-prefix" . }}-self-signed
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
# Create the CA cert for the dex issuer.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubee-name-prefix" . }}-ca
  namespace: {{ .Values.namespace }}
spec:
  {{- /* Secret Name that will store the certificate (ie private key and certificate) */}}
  secretName: {{ include "kubee-name-prefix" . }}-ca
  commonName: "{{ (include "kubee-to-camel-case" .Release.Name)}} {{ include "kubee-to-camel-case"  (include "kubee-prefix" .)}} Ca"
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - cluster.local
      - cert-manager
  duration: '87600h'  # ie 3650 days, 10 years,, default to 90 days
  issuerRef:
    kind: Issuer
    name: {{ include "kubee-name-prefix" . }}-self-signed
  usages:
    - any
---
# The dex issuer using the CA keypair (Ca certificate)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuers.kubee_ca.name }}
  namespace: {{.Values.namespace}}
spec:
  ca:
    {{- /* Name of the certificate (ie private key and certificate) */}}
    secretName: {{ include "kubee-name-prefix" . }}-ca
