# Not a string, a boolean so no quote
enabled: false
# namespace
namespace: 'monitoring'
# The type of instance:
# * external: monitoring via api
# * internal: (not yet supported) installation of healthchecks in the cluster
#             ie https://github.com/healthchecks/healthchecks
type: external
# hostname
hostname: 'healthchecks.io'
# api key
# https://healthchecks.io/docs/configuring_prometheus/
# The auth credential (used for an external instance)
read_only_api_key: ''
# projects uuid
# https://healthchecks.io/docs/configuring_prometheus/
project_uuids: []