---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  namespace: {{.Values.namespace}}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if eq .Values.cert_manager.enabled true}}
    cert-manager.io/cluster-issuer: {{.Values.cert_manager.issuer_name}}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.hostname}}
      http:
        paths:
          - backend:
              service:
                name: {{ template "dex-service-name" }}
                port:
                  number: 5556
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{.Values.hostname}}
      secretName: {{ template "dex-cert-name"}}
