apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example


resources:
- prometheus-example-deployment.yml
- prometheus-example-service.yml
- prometheus-example-service-monitor.yml


generatorOptions:
  # disable appending a content hash suffix to the names of generated resources
  disableNameSuffixHash: true
  # adding labels to generated resources
  labels:
    generator: argocd