apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: '{{ .Release.Name }}-{{ .Values.cloudflareApiToken.secretNameSuffix }}'
  namespace: '{{ include "cert-manager.namespace" . }}'
spec:
  # The store from where
  secretStoreRef:
    name: vault-external-secret-store
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: '{{ .Release.Name }}-{{ .Values.cloudflareApiToken.secretNameSuffix }}' # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Cloudflare Api Token"
  # Mapping to local secret from remote secret
  data:
    - secretKey: {{ .Values.cloudflareApiToken.secretKey }} # Prop Name in the secret
      remoteRef:
        key: cloudflare # Name of the remote secret
        property: cert-manager-api-token # Prop Name in the remote secret


