---
repos:
  - repo: https://github.com/dadav/helm-schema
    rev: 0.18.1
    hooks:
      - id: helm-schema
        # for all available options: helm-schema -h
        args:
          # directory to search recursively within for charts
          - --chart-search-root=resources/charts/stable/mailpit

          # don't analyze dependencies
          # - --no-dependencies

          # Add references line as header in the values.yaml file if not exist
          # - --add-schema-reference

          # helm docs compat
          - --helm-docs-compatibility-mode

          # append newline to generated jsonschema at the end of the file
          - --append-newline

          # list of fields to skip from being created by default
          # e.g. generate a relatively permissive schema
          # - "--skip-auto-generation=required,additionalProperties"