# Used to generate the doc, see task readme
apiVersion: v2
name: Kubee
description: Kubee, Kubernetes, the Easy way. Single VPS Hosting and beyond

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0 # The version of the chart (doesn't matter and can stay the same)

# This is the version number of the application being deployed.
# The version of prometheus operator
appVersion: "0.0.0"
