version: '3'

tasks:
  # Generate the readme
  readme:
    cmds:
      - |
        OUTPUT_DIR=out/README
        mkdir -p "$OUTPUT_DIR"
        cp "Chart.yaml" "$OUTPUT_DIR"
        cp "README.md.gotmpl" "$OUTPUT_DIR"
        MODEL_PATH="$OUTPUT_DIR/model.yaml"
        CHARTS_PATH="charts"
        yq '{.name: { "description": .description, "appVersion": .appVersion, "type": .annotations."chart.kubee/type" // "na", "status": .annotations."chart.kubee/status" // "na", "kind": (.annotations."chart.kubee/kinds" | from_yaml), "deprecated": .annotations.deprecated  // false }} | . as $item ireduce ({}; . * $item )' $(find "$CHARTS_PATH" -maxdepth 2 -type f  -name "Chart.yaml") > $MODEL_PATH
        # Path argument in helm-docs should be relative to chart-search-root (not absolute ...)
        (cd $OUTPUT_DIR; helm-docs)
        cp "$OUTPUT_DIR/README.md" "README.md"
        
  
      
      
