# Enabled or not
enabled: false
# The namespace
namespace: 'oauth2-proxy'
# the hostname
hostname: ''
# Auth
auth:
  # Secret Mandatory: A random value used to sign cookies
  # Example command : openssl rand -base64 32
  # Example value   : bc989147a1d2ff433933b39b40b9b1d0
  cookie_secret: ''
  # Cookie Expiration
  # Default is 168h (ie 7 days)
  cookie_expire: "168h"
  cookie_domains: []
  # Email Domains
  # Only users with this domain will be let in
  # Accepted value: `*` for all emails or `your.company.com`
  email_domains: [ '*' ]
  #
  # whitelist domains
  whitelist_domains: []
oauth2_proxy:
  httpScheme: https
  config:
    # We use our own secret
    existingSecret: oauth2-proxy
    # We use our own config
    existingConfig: oauth2-proxy
# Internal, don't change
kubee_internal:
  install_cross_dependency: false
