{{/*
  https://external-secrets.io/latest/provider/hashicorp-vault/
  https://external-secrets.io/v0.9.20/api/clustersecretstore/

  Test:
  helm template -s templates/cluster-secret-store-vault.yaml \
    --set 'vault.api_token=xxx'  \
    --set 'vault.enabled=true'  \
    . | yq
*/}}
{{- if and (ne .Values.store.vault.api_token "") (eq .Values.vault.enabled true) -}}
apiVersion: external-secrets.io/v1beta1
# cluster scoped SecretStore
kind: ClusterSecretStore
metadata:
  name: '{{ required "external_secrets.store.name is required" .Values.store.name }}'
  namespace: "{{ .Values.namespace }}"
spec:
  provider:
    vault:
      # server
      server: "http://vault.{{ .Values.vault.namespace }}:8200"
      # path of the engine
      path: "{{ .Values.vault.engines.default.mount_path }}"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      # noinspection KubernetesUnknownValues
      version: "v{{ .Values.vault.engines.default.version }}"
      auth:
        # Points to the below secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "{{ template "external-secrets-vault-secret-name" . }}"
          namespace: "{{ .Values.namespace }}"
          key: "{{ template "external-secrets-vault-secret-key" }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "external-secrets-vault-secret-name" . }}"
  namespace: "{{ .Values.namespace }}"
data:
  {{ template "external-secrets-vault-secret-key" }}: '{{ .Values.store.vault.api_token | b64enc }}'
{{- end -}}
