apiVersion: v2
name: kubee-external-secrets
description: Kubee External Secrets Charts

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.14.3" # The version of the app packaged

annotations:
  app.kubernetes.io/name: "external-secrets"
  chart.kubee/status: "stable"
  chart.kubee/kind: "app"
  chart.kubee/category: "secret"
  chart.kubee/crds: |
    - name: kubee-external-secrets-crds
      version: 0.14.3
      repository: file://../external-secrets-crds

# https://github.com/external-secrets/external-secrets/releases
dependencies:
  - name: external-secrets
    version: 0.14.3
    repository: https://charts.external-secrets.io
    alias: external-secrets
    #condition: external-secrets.enabled
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  - name: kubee-vault
    version: 0.0.1
    repository: file://../vault
    alias: vault
