{{/*
  https://grafana.github.io/grafana-operator/docs/datasources/
*/}}
{{- if eq .Values.prometheus.enabled true -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "{{ .Values.name }}"
  datasource:
    {{- /* this is it, this is the name seen in the prompt ....    */}}
    uid: {{ .Values.data_sources.prometheus.name }}
    {{- /* this is a display name, seen only on the edit form  */}}
    name: {{ .Values.data_sources.prometheus.name }}
    {{- /* sometimes dashboard use just default */}}
    isDefault: true
    type: prometheus
    access: proxy
    {{- /* prometheus-name is the default name of kube-prometheus */}}
    url: http://prometheus-{{ .Values.prometheus.name }}.{{ .Values.prometheus.namespace }}:9090
    {{- /* Json Data: https://github.com/grafana/grafana/blob/2c2ac096fe66df155b68f1578bfc1137e7af53e8/public/app/plugins/datasource/prometheus/types.ts#L38  */}}
    jsonData:
      tlsSkipVerify: true
      {{- /* Scrape interval is time interval*/}}
      {{- /* https://stackoverflow.com/questions/66369969/set-scrape-interval-in-provisioned-prometheus-data-source-in-grafana*/}}
      timeInterval: "{{.Values.prometheus.scrape_interval}}"
      queryTimeout: "59s"
{{- end -}}