{{ $ := mergeOverwrite $ (dict "component" "smtp") }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.conf_kube.smtp_server.service_name}}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    {{- include "kubee-pod-labels" . | indent 4}}
  ports:
    - name: smtp
      # This port is shown in the UI as configuration instruction
      # That's why we use the same
      port: {{.Values.conf_yaml.smtp_server.default_port}}
      targetPort: smtp
    - name: health
      port: {{.Values.conf_yaml.smtp_server.default_health_server_port}}
      targetPort: health


