# Ref: https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/

# This is a list of rule files to consider for testing. Globs are supported.
rule_files:
  - batch-job-alert-rules.yml

evaluation_interval: 1m # default = 1m

# The order in which group names are listed below will be the order of evaluation of
# rule groups (at a given evaluation time). The order is guaranteed only for the groups mentioned below.
# All the groups need not be mentioned below.
#group_eval_order:
#  [ - <group_name> ]

# All the tests are listed here.
tests:
  # Test 1.
  - name: Batch Job Test
    # Time between interval in the series
    interval: 1m
    # Series data.
    input_series:
      # Ref: https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/#series
      - series: 'push_time_seconds{job="git_hosting_backup"}'
        # 10 scrapes at 1min interval with the same value, ie 1731433061 or 2024/11/12 17:37:41
        values: '1731433061+0x10'
    # Unit tests for promql expressions.
    promql_expr_test:
      # Unit test 1 / Testcase
      # Ref: https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/#promql_test_case
      # Diff at minima: 606361
      # time() - 1731433061 > bool 606387
      # vector(0)
      - expr: 'push_time_seconds{job="git_hosting_backup"} > time() - 60*60*24*7'
        # The coordinate in time elapsed (number of scrape points used in the series, you see them with `promtool test --debug` option)
        eval_time: 5m
        # If the query does not return any series (ie expression in the left part), you have to provide an empty list to exp_samples.
        # otherwise you get a FAILED with `got: nil`
        exp_samples:
          # Sample 1.
          - labels: 'push_time_seconds{job="git_hosting_backup"}'
            value: 1731433061

    # Unit test for alerting rules.
    alert_rule_test:
      # Unit test 1
      # https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/#alert_test_case
      # Alert name to be tested
      - alertname: BatchDown
        # The time elapsed from time=0s when the alerts have to be checked.
        # The coordinate in time elapsed (number of scrape points used in the series, you see them with `promtool test --debug` option)
        eval_time: 5m
        # List of expected alerts which are firing under the given alertname at given evaluation time.
        # An empty list means we expect no alert
        exp_alerts:
          # Alert 1.
          - exp_labels:
              severity: critical
              job: git_hosting_backup
            exp_annotations:
              summary: "Git hosting backup batch has failed to run"
              description: "Git hosting backup should push metrics at least once every week"

