#!/usr/bin/env bash

# This script update the version
# and crd from the upstream sub-chart

source bashlib-error.sh
error::set_strict_mode
error::set_trap
source bashlib-echo.sh

# this works for executed script or sourced script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
BASENAME=$(basename "$SCRIPT_DIR")
NAME="external secret"

# Get the Traefik chart
CHART_VERSION=$(yq '.dependencies[] | select(.name == "external-secrets") | .version' "$SCRIPT_DIR/../../apps/$BASENAME/Chart.yaml" | tr -d '~' )
if [ "$CHART_VERSION" == "" ]; then
  echo::err "Unable to retrieve the $NAME chart version (the value was empty)"
  exit 1
fi
echo::info "Updating crds for the $NAME chart $CHART_VERSION"

APP_VERSION="0.0.1"


echo::info "Updating crds Chart.yml with app version: $APP_VERSION. Chart: $CHART_VERSION"
yq ".appVersion = \"$CHART_VERSION\"" -i Chart.yaml
yq ".version = \"$APP_VERSION\"" -i Chart.yaml

echo::info "Download the CRD of $NAME $CHART_VERSION"
curl \
  -s \
  -o "templates/crds.yaml" \
  --fail \
  "https://raw.githubusercontent.com/external-secrets/external-secrets/v${CHART_VERSION}/deploy/crds/bundle.yaml"

echo::success "The $NAME chart was updated"