# Bootstrap and common cluster values (ie global)

# Cluster Wide variables
cluster:
  # The cluster name
  # used:
  # * to identify the cluster (for instance, on prometheus remote-write metrics, the name is added as label)
  # * as default first instance name for operator (for instance, prometheus operator allows to install multiple prometheus that needs to be unique. Kube-prometheus asks for a unique name)
  name: 'kubee'

# Authentication
auth:

  # The admin user
  #  * created as admin user in Kubernetes and other app
  #  * added in basicAuth
  admin_user:
    username: 'admin'
    # The password
    password: ''
    # Kubernetes clusterRole
    # * `cluster-admin` has full access
    # * `admin` does not have access to node and cluster scope related object such as ClusterRoleBinding
    clusterRole: 'cluster-admin'
    # The email
    # It's used by default in apps. For instance:
    # * letsencrypt registration email
    # * alert notifications: prometheus, argocd
    email: ''

  # Trusted Proxy
  # If trusted, reverse_proxy handler will proxy and augment the sensitive X-Forwarded-* request headers.
  # You should set the CIDR value of:
  # * internal proxy such as traefik
  # * and external proxy such as cloudflare
  trusted_proxies: []


# email
email:
  # Default smtp server parameters
  smtp:
    # The smtp host
    # if the host is not empty, smtp configuration are added
    # for example for argocd email notifications
    host: ''
    # the smtp port
    port: ''
    # the default from
    from: ''
    # the auth connection username
    username: ''
    # the auth connection password
    password: ''
    # hello (used to present itself, normally the email apex domain name)
    hello: ''
