{{ $ := mergeOverwrite $ (dict "component" "web") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-manifest-labels" . | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
        - name: web
          command: [ "postal", "web-server" ]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
          ports:
            - name: 'web'
              containerPort: {{ .Values.conf_yaml.web_server.default_port }}
      {{- include "postal-deploy-containers-common" . | indent 6}}
