{{ $ := mergeOverwrite $ (dict "component" "web") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-manifest-labels" . | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
        - name: web
          image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
          command: [ "postal", "web-server" ]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
          env:
            - name: MAIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: mariadb-password
            - name: MESSAGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: mariadb-password
            - name: RAILS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: rails-secret-key
          ports:
            - name: web
              containerPort: {{ .Values.conf_yaml.web_server.default_port }}
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          volumeMounts:
            - name: config-map
              mountPath: /config/postal.yml
              subPath: postal.yml
              readOnly: true
            - name: config-secret
              # This is the default $config-file-root/signing.key
              mountPath: /config/signing.key
              subPath: dkim-signing-key
              readOnly: true
            - name: smtp-tls
              mountPath: /config/certs
              readOnly: true
      volumes:
        - name: config-map
          secret:
            secretName: {{ include "postal-name-config-map" . }}
        - name: config-secret
          secret:
            secretName: '{{ include "postal-name-config-secret" . }}'
        - name: smtp-tls
          secret:
            secretName: '{{ include "postal-name-tls" . }}'