{{ $ := mergeOverwrite $ (dict "component" "web") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-manifest-labels" . | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
      - name: web
        image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
        command: ["postal", "web-server"]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
        ports:
        - name: web
          containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: {{ include "postal-name-postal-yml" . }}