{{/* Context */}}
{{ $ := mergeOverwrite $ (dict "component" "web") }}
{{ $tlsComponent := "tls" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
  annotations:
    {{- if not .Values.traefik.enabled }}
    {{- fail "traefik should be enabled to apply the ingress" }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: '{{ .Values.traefik.namespace }}-{{.Values.traefik.middlewares.auth_headers.name}}@kubernetescrd'
    {{- if not .Values.cert_manager.enabled }}
    {{- fail "cert_manager should be enabled to apply a secure ingress" }}
    {{- end }}
    cert-manager.io/cluster-issuer: {{.Values.cert_manager.issuers.public.name}}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kubee-name" . }}
                port:
                  number: 5000
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ include "kubee-name" (merge . (dict "component" $tlsComponent)) }}