apiVersion: v1
kind: Service
metadata:
  name: {{ include "postal-name" . }}-web
  labels:
    app.kubernetes.io/name: postal
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "postal.name" . }}
    component: web
  ports:
  - name: web
    port: 5000
    targetPort: web
