{{ $ := mergeOverwrite $ (dict "component" "web") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    {{- include "kubee-pod-labels" . | indent 4}}
  ports:
  - name: web
    port: 80
    targetPort: web
