# All these values are used in sub-chart
# to create template manifest

# Cluster Wide variables
cluster:
  # Admin user
  #  * created as admin user in Kubernetes and other app)
  #  * added in basicAuth
  adminUser:
    username: 'admin'
    password: ''
    # Kubernetes clusterRole
    # * `cluster-admin` has full access
    # * `admin` does not have access to node and cluster scope related object such as ClusterRoleBinding
    clusterRole: 'cluster-admin'
  # Authentication of internal infra website such as Traefik Dashboard, ...
  auth: basicAuth


# Templating variables
# Template is a reserved name
templates:
  # The prefix added to all name created by kube-x template
  globalPrefix: "kube-x"
  
# Kube-X Dashboard Variables
kubernetes_dashboard:
  # The external DNS
  hostname: 'dash.kube-x.dev'

# Kube-X Traefik Variables
traefik:
  # Instance/Release Name
  namespace: traefik
  middleware:
    # Enabled by default when the admin user password is not empty
    # https://doc.traefik.io/traefik/middlewares/http/basicauth/
    basicAuth:
      # List of users
      users:
      # user1: password1
  cert:
    # Set the kube-x.dev certificate as default traefik cert
    # Mandatory for kubernetes-dashboard
    # If true, the rootCA should be added to the OS/Browser as trusted root CA
    kubeXDevAsDefault: false
  dashboard:
    # The FQDN is dnsName.apexDomain
    hostname: 'traefik.kube-x.dev'

# The prometheus kube-x env
prometheus:
  enabled: false

# The cert manager kube-x env
cert_manager:
  enabled: false
  issuerName:

whoami:
  hostname: 'whoami.kube-x.dev'


