# Service for Traefik to talk to Forward-Auth.
apiVersion: v1
kind: Service
metadata:
  name: forward-auth
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: forward-auth
  ports:
    - port: {{ template "traefik-forward-auth-port" }}
