# Expose forward-auth to the internet for OAuth initialization and callbacks.
# https://github.com/thomseddon/traefik-forward-auth/blob/master/examples/traefik-v2/kubernetes/advanced-separate-pod/traefik-forward-auth/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-forward-auth
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- .Values.cert_manager.enabled |  required "Cert Manager is not enabled and is required"  }}
    cert-manager.io/cluster-issuer: '{{ .Values.cert_manager.issuer_name }}'
spec:
  ingressClassName: traefik
  rules:
    - host: '{{ required "The forward-auth hostname is required" .Values.hostname }}'
      http:
        paths:
          - backend:
              service:
                name: 'forward-auth'
                port:
                  number: {{ template "traefik-forward-auth-port" }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - '{{ .Values.hostname }}'
      secretName: 'traefik-forward-auth-cert'