apiVersion: v2
name: kubee-oauth2-proxy
description: Kubee Oauth2-Proxy Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1 # The version of the chart (doesn't matter and can stay the same)

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "7.8.1" # The oauth2 proxy version

annotations:
  chart.kubee/status: "stable"
  chart.kubee/kind: "app"
  chart.kubee/category: "auth"
  chart.kubee/engines: |
    - helm

dependencies:
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  # For the client id and secret
  - name: kubee-dex
    version: 0.0.1
    repository: file://../dex
    alias: dex
    condition: kubee_internal.install_cross_dependency
  # For the scrape
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
  # For the cert and the kubee ca issuer
  - name: kubee-cert-manager
    version: 0.0.1
    repository: file://../cert-manager
    alias: cert_manager
    condition: kubee_internal.install_cross_dependency
  # For the middleware
  - name: kubee-traefik
    version: 0.0.1
    repository: file://../traefik
    alias: traefik
    condition: kubee_internal.install_cross_dependency
