{{- if (ne .Values.hostname "") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pushgateway
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Because Middleware is not namespace, we use the kube-system-traefik-dashboard-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-traefik-dashboard-auth@kubernetescrd
    {{- if ne ((.Values).cert_manager).enabled false }}
    cert-manager.io/cluster-issuer: '{{ .Values.cert_manager.issuer_name }}'
    {{- end }}
spec:
  rules:
    - host: {{ required "hostname is required" .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: pushgateway
                port:
                  number: 9091
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: pushgateway-cert
{{- end}}