# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'monitoring'

# @schema
# title: Hostname
# description: The public hostname
# required: true
# minLength: 1
# format: hostname
# @schema
# -- The public hostname (Create an authenticated ingress if not empty)
hostname: ''

# -- The [pushgateway version](https://hub.docker.com/r/prom/pushgateway)
version: 'v1.10.0'

# -- Enable Metrics Persistence on a volume
persistence:
  # Enable
  enabled: true
  # Size of the volume
  size: 50Mi
  # Interval to flush the metrics to the persistence file.
  interval: '5m'
  # Storage Class (The volume manager)
  # By default, [k3s local-path](https://docs.k3s.io/storage#setting-up-the-local-storage-provider)
  storage_class: local-path


# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false
