{{/*
  https://grafana.github.io/grafana-operator/docs/datasources/
*/}}
{{- if eq .Values.prometheus.enabled true -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "{{ .Values.name }}"
  datasource:
    name: {{ .Values.data_sources.prometheus.name }} # used by default by mixins
    isDefault: true # sometimes they use just default
    type: prometheus
    access: proxy
    {{/* prometheus-name is the default name of kube-prometheus */}}
    url: http://prometheus-{{ .Values.prometheus.name }}.{{ .Values.prometheus.namespace }}:9090
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
{{- end -}}