# Enabled
enabled: false
# Installation Namespace (same as traefik)
namespace: 'kube-system'
# The hostname (mandatory) for external dns access for callback by providers such as dex
hostname: ''
# Service name for internal dns access by the traefik middleware
service: 'traefik-forward-auth'
# Docker Hub Version
# https://hub.docker.com/r/thomseddon/traefik-forward-auth/tags
# Unfortunately, the last release is not on Docker
# https://github.com/thomseddon/traefik-forward-auth/issues/373
# We use the v2.2.0 instead of the v2.3.0
version: 'v2.2.0'
# Auth Parameters
auth:
  # Secret Mandatory: A random value used to sign cookies
  # Example command : openssl rand -base64 32
  # Example value   : bc989147a1d2ff433933b39b40b9b1d0
  cookie_secret: ''
  # If set, the cookie is set to the domain level
  # creating an SSO experience
  # Comma separated of apex domain
  # https://github.com/thomseddon/traefik-forward-auth#auth-host-mode
  cookie_domains: ''
  # Session Lifetime in seconds, ie cookie (12 hours)
  cookie_lifetime: 43200
  # Allow only given email addresses
  # Comma separated list of emails
  whitelist_email_addresses: ''
  # When set, only users matching a given domain will be permitted to access.
  # With example.com, thom@example.com would be allowed but thom@another.com would not.
  # Comma separated list of domain
  whitelist_email_domains: ''

# Auth configuration
# Internal
kubee_internal:
  install_cross_dependency: false