#!/usr/bin/env bash

# This scripts gather dependent script


source bashlib-error.sh
error::set_strict_mode
error::set_trap
source bashlib-echo.sh


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR"/../../prometheus/utilities/prometheus-dependency-helper --jsonnet-dir="$SCRIPT_DIR/../jsonnet"
