apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  selector:
    app.kubernetes.io/name: gogs
  ports:
    - name: ssh
      protocol: TCP
      port: 10022
      targetPort: 22
      nodePort: 30022
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
