---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth2-proxy-service-account-name" .}}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{.Release.Name}}
automountServiceAccountToken: true
