{{/*
Test:
helm template -s templates/whoami-ingress.yml --set 'kubee.cert_manager.enabled=true' .
*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "whoami-name" . }}'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if ne (((.Values.kubee).cert_manager).enabled) false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kubee.cert_manager.defaultIssuerName }}'
    {{- end }}
spec:
  rules:
    - host: '{{ .Values.kubee.whoami.hostname }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ include "whoami-name" . }}'
                port:
                  number: 80
            path: /
            pathType: Prefix
  {{- if ne (((.Values.kubee).cert_manager).enabled) false }}
  tls:
    - hosts:
        - '{{ .Values.kubee.whoami.hostname }}'
      secretName: '{{ include "whoami-name" . }}'
  {{- end }}
---
