{{/*
Test:
helm template -s templates/whoami-ingress.yml --set 'cert_manager.enabled=true' .
*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "whoami-name" . }}'
  namespace: '{{ .Values.namespace }}'
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if .Values.auth_middleware }}
    traefik.ingress.kubernetes.io/router.middlewares: '{{ .Values.traefik.namespace }}-{{ .Values.auth_middleware }}@kubernetescrd'
    {{- end }}
    {{- if ne .Values.cert_manager.enabled false }}
    cert-manager.io/cluster-issuer: '{{ .Values.cert_manager.issuer_name }}'
    {{- end }}
spec:
  rules:
    {{ $hostnames := list .Values.hostname}}
    {{- range $hostname := $hostnames }}
    - host: '{{ $hostname }}'
      http:
        paths:
          - backend:
              service:
                name: '{{ include "whoami-name" (dict "Release" $.Release ) }}'
                port:
                  number: 80
            path: /
            pathType: Prefix
    {{- end }}
  {{- if ne .Values.cert_manager.enabled false }}
  tls:
    {{- range $i, $hostname := $hostnames }}
    - hosts:
        - '{{ $hostname }}'
      secretName: '{{ include "whoami-name" (dict "Release" $.Release ) }}-{{ $i }}'
    {{- end }}
  {{- end }}