apiVersion: v1
kind: Service
metadata:
  name: '{{ include "whoami-name" . }}'
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/name: '{{ .Release.Name }}'
spec:
  # ClusterIp is the default
  type: ClusterIP
  selector:
    app.kubernetes.io/name: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
