# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false
# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace (create an ingress if not empty)
namespace: 'monitoring'

# @schema
# title: Hostname
# description: The public hostname
# required: true
# minLength: 1
# format: hostname
# @schema
# -- The public hostname
hostname: ''


# -- The [alert manager version](https://github.com/prometheus/alertmanager/releases)
version: "0.28.0"

# @schema
# const: kubee
# @schema
# @ignored Instance name
# The operator uses it to create unique alertmanager
# It's also a Kube-Prometheus mandatory variable
name: 'kubee'


resources:
  # -- Memory
  memory: '50Mi'


# -- `Watchdog`: the receiver of the [watchdog alert](https://runbooks.prometheus-operator.dev/runbooks/general/watchdog)
# Example of cron monitoring system: https://healthchecks.io/
watchdog:
  # Email address (to check if we can send email)
  email:
    to: ''
    # The interval of notification (By default, one email every 12 hours)
    repeat_interval: '12h'
  # WebHook Url (to check if prometheus is still up)
  webhook:
    url: ''
    # The interval of notification (By default, one http request every 10 min)
    repeat_interval: '10m'


opsgenie:
  # -- Opsgenie Api Key to send alert. If the api key is not empty,
  # critical and warning alerts are sent to opsgenie
  api_key: ''

# @ignored - Not yet finished - [Pager Duty](https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config)
pagerduty:
  # The service key is known as integration key in pagerduty documentation
  service_key: ''
  # The url is known as integration url in pager duty documentation
  url: 'https://events.eu.pagerduty.com/generic/2010-04-15/create_event.json'


# Secret
secret:
  # @schema
  # enum: [ 'Secret', 'ExternalSecret' ]
  # @schema
  # -- The kind of Secret manifest created
  kind: 'Secret'


# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false
