apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    # Selects all Service objects with the `app: example-app` label.
    matchLabels:
      app: example-app
  endpoints:
    - port: web
