{{- /*
https://doc.traefik.io/traefik/middlewares/http/basicauth/

Enable only when the admin password is not empty

Test:
helm template -s templates/traefik-middleware-basic-auth.yml --set 'cluster.auth.admin_user.password=yolo' .

Note: Operators are functions (ne is a function with 2 args)
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#operators-are-functions
*/}}
{{- if ne .Values.cluster.auth.admin_user.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.middlewares.basic_auth.name }}'
  namespace: '{{ .Values.namespace }}'
{{- /*#
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
  {{- /* one user by line*/}}
  users: |{{- include "basic-auth-list-base64-encode" . | indent 4}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: '{{ .Values.middlewares.basic_auth.name }}'
  namespace: '{{ .Values.namespace }}'
spec:
  basicAuth:
    secret: '{{ .Values.middlewares.basic_auth.name }}'
{{- end}}