# Forward authentication Middleware that passes the bearer
# Oauth Proxy Doc: https://oauth2-proxy.github.io/oauth2-proxy/configuration/integration#configuring-for-use-with-the-traefik-v2-forwardauth-middleware
# Traefik Doc: https://doc.traefik.io/traefik/middlewares/http/forwardauth/#configuration-examples
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{.Values.middlewares.forward_auth_bearer.name }}
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: "https://oauth2-proxy.{{ .Values.oauth2_proxy.namespace }}.svc.cluster.local"
    # https://doc.traefik.io/traefik/middlewares/http/forwardauth/#insecureskipverify
    tls:
      insecureSkipVerify: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization