{{- if ne .Values.prometheus.enabled false -}}
{{- $component := "metrics" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubee-name" (dict "Chart" .Chart "component" $component) }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "kubee-manifest-labels" (dict "Chart" $.Chart "Release" $.Release "component" $component) | nindent 4}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: 'traefik-{{.Values.namespace}}'
  ports:
  - port: 9100
    name: "metrics"
    targetPort: metrics
    protocol: TCP
{{- end }}