# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'external-dns'


# -- Image with the [External DNS version](https://github.com/kubernetes-sigs/external-dns/releases)
image: registry.k8s.io/external-dns/external-dns:v0.15.1
# It's not always published right-away in the kubernetes registry. You can check it on the [Helm Chart](https://github.com/kubernetes-sigs/external-dns/blob/external-dns-helm-chart-1.15.2/charts/external-dns/Chart.yaml)
# And official staging images are also available at:
# https://console.cloud.google.com/gcr/images/k8s-staging-external-dns/global/external-dns?inv=1&invt=Abr7-w&walkthrough_id=panels--container-registry--images

server:
  # @ignored Log
  log:
    # @schema
    # enum: [panic, debug, info, warning, error, fatal]
    # @schema
    # Log level
    level: info
    # @schema
    # enum: [text, json]
    # @schema
    # Log format.
    format: text
  # @ignored The metadata store
  registry:
    # @schema
    # enum: [ 'txt', 'aws-sd', 'dynamodb', 'noop' ]
    # @schema
    # [Registry](https://kubernetes-sigs.github.io/external-dns/latest/docs/registry/registry/)
    # where to persist metadata such as [ownership of record](https://kubernetes-sigs.github.io/external-dns/latest/docs/initial-design/#ownership) to not overwrite records not managed by External DNS
    # `txt` stores DNS record metadata in TXT records
    type: 'txt'
    txt:
      # @schema
      # minLength: 1
      # @schema
      # A name that identifies this instance of ExternalDNS
      owner_id: "kubee"
      # Txt record prefix
      # It should contain record type template like 'prefix-%{record_type}-'. Mutual exclusive with txt-suffix!
      # `%{record_type}` should be included, as any other value will cause a weird duplication of database records.
      # This is optional, but we set a default
      # otherwise apex records are not created as you may have txt field for site verification
      prefix: 'kubee-%{record_type}-'
      # A custom string that's suffixed to the host portion of each ownership DNS record (optional).
      # Could contain record type template like '-%{record_type}-suffix'. Mutual exclusive with txt-prefix!
      # `%{record_type}` should be included, as any other value will cause a weird duplication of database records.
      suffix: ''
      # @schema
      # type: boolean
      # @schema
      # Encrypt
      # Key is mandatory if true
      encrypt: false
      # Set TXT record decryption and encryption 32 byte aes key (required when --txt-encrypt=true)
      encrypt_aes_key: ''

  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # @ignored [Source](https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/about/)
  sources: []

  # @schema
  # type: boolean
  # @schema
  # @ignored When auto-source is enabled, the following sources are added:
  # [service](https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/service/). for services without ingress such as loadbalancer
  # [ingress](https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/ingress/)
  # [Crd](https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/crd/)
  # [traefik](https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/traefik-proxy/) if enabled in the cluster file
  auto_sources: true


  # -- Interval for DNS sync.
  interval: '1m'

  # -- The local DNS cache to avoid [rate limiting](https://kubernetes-sigs.github.io/external-dns/latest/docs/rate-limits/)
  # If a DNS entry is deleted/modified manually, the recovery will need to wait this interval for resynchronization.
  # Or you need to restart the pod.
  # You turned if off with the value `0m`, or you empty the cache by restarting the pod
  cache_time: '0m'

  # @schema
  # const: false
  # @schema
  # @ignored For info, ExternalDNS does not in a namespaced scope (Role and RoleBinding are cluster role).
  # We don't support a namespaced scope
  namespaced: false

  # @ignored Record Type Filtering
  record_filtering:
    # @schema
    # type: array
    # items:
    #    enum: [A, AAAA, CNAME, NS, SRV, MX, TXT, NAPTR]
    # @schema
    # Record types to manage
    managed: # [Ref](https://github.com/kubernetes-sigs/external-dns/blob/724b86b8b867db9420c51b6a8bc9d26118bf213d/pkg/apis/externaldns/types.go#L471C110-L471C124)
      - A
      - AAAA
      - CNAME
      - TXT
      - MX
      - SRV
    # @schema
    # type: array
    # items:
    #    enum: [A, AAAA, CNAME, NS, SRV, MX, TXT, NAPTR]
    # @schema
    # Record types to exclude
    exclude: [ ] # [Ref](https://github.com/kubernetes-sigs/external-dns/blob/724b86b8b867db9420c51b6a8bc9d26118bf213d/pkg/apis/externaldns/types.go#L472)

  # @schema
  # enum: [upsert-only, sync]
  # @schema
  # -- Policy Synchronization.
  # `upsert-only`: Prevent deleting any records.
  # `sync`: if you want DNS entries to get deleted as well
  policy: upsert-only

  # The URL of the remote endpoint to call for the webhook provider (default: http://localhost:8888)")
  # url: 'http://localhost:8888'
  # @ignored The read timeout for the webhook provider in duration format (default: 5s)
  webhook_read_timeout: '5s'
  # @ignored The write timeout for the webhook provider in duration format (default: 10s)
  webhook_write_timeout: '10s'


# The provider
# Only [one provider is currently supported](https://github.com/kubernetes-sigs/external-dns/issues/2568)
# Default to cloudflare if the api_key and the dns zones are specified in the cluster chart
# https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/webhook-provider/
# The ideal setup for providers is to run as a sidecar in the same pod of the ExternalDNS container, listening only on localhost
provider:
  # @schema
  # enum: ['in-tree','webhook']
  # @schema
  # -- Provider. `in-tree` or `webhook`
  type: 'in-tree'
  # -- The name of the provider (Required for an in-tree provider)
  name: ''
  # -- The webhook provider image.
  # Required if the provider is `webhook`.
  # `in-tree` uses the `external-dns` image as webhook provider.
  # Example: `ghcr.io/mconfalonieri/external-dns-hetzner-webhook:v0.7.0`
  image: ''
  # @ignored Endpoints
  endpoints:
    # The webhook/http  port
    webhook:
      # @schema
      # type: integer
      # @schema
      # The webhook port
      port: 8888
    # The metrics
    metrics:
      # @schema
      # type: integer
      # @schema
      # The metrics port (Not 7979 as this is already taken by external-dns)
      port: 8080 # 8080 is the [Default](https://kubernetes-sigs.github.io/external-dns/v0.14.2/tutorials/webhook-provider/#metrics-support)
      path: /metrics
    # The health
    health:
      # @schema
      # type: integer
      # @schema
      # The health port (Not 7979 as this is already taken by external-dns)
      # By default, this is the same value as for the metrics
      port: 8080 # 8080 is the [Default](https://kubernetes-sigs.github.io/external-dns/v0.14.2/tutorials/webhook-provider/#metrics-support)
      path: /healthz  # Some webhook use health in place of [healthz](https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/webhook-provider/#exposed-endpoints)
  # @schema
  # type: "array"
  # items:
  #   type: string
  #   examples: [ '--aws-batch-change-interval=1s' ]
  # @schema
  # -- An array of args to be added to the external dns server
  # Providers are driven by some args. Refer to their documentation to discover them.
  args: [ ]
  # @schema
  # type: "array"
  # items:
  #   type: object
  #   properties:
  #     name:
  #       title: an env name
  #       type: string
  #       examples: [DNSIMPLE_OAUTH]
  #     value:
  #       title: an env value
  #       type: string
  #       examples: [YOUR_DNSIMPLE_API_KEY]
  # @schema
  # -- An array of name, value env stored in secrets and passed as env.
  # Providers secret are driven by env. Refer to their documentation to discover them.
  env: [ ]
  # In-tree Provider common arguments
  in_tree:
    # @ignored Log
    log:
      # @schema
      # enum: [panic, debug, info, warning, error, fatal]
      # @schema
      # Log level
      level: info
      # @schema
      # enum: [text, json]
      # @schema
      # Log format.
      format: text
    # @ignored Request Timeout
    request_timeout: '30s'
    # @schema
    # type: array
    # items:
    #   type: string
    #   format: hostname
    #   examples: ['10.0.0.in-addr.arpa']
    # @schema
    # -- Domain filter. Limit to only domains; change to match the zone
    # Create DNS records for host names that match
    # E.g.
    # `example.org` will allow the zone `example.org` and all subdomains (ie `xx.example.org`)
    # `a.example.com` will allow for zone `example.com`
    # `.example.com` will not attempt to match parent zones.
    domain_filter: [ ]
    # -- Limits possible domains and target zone with a regex.
    # It overrides domain filters and can be specified only once.
    # Example: `(example\\.org|company\\.com)$` or `example*`
    regex_domain_filter: ''
    # @schema
    # type: array
    # items:
    #   type: string
    #   format: hostname
    #   examples: ['10.0.0.in-addr.arpa']
    # @schema
    # -- Exclude a domain or subdomain
    # Example: `ignore.this.example.com`
    exclude_domains: [ ]
    # @ignored (optional) limit to a specific zone.
    # example value: `023e105f4ecef8ad9ca31a8372d0c353`
    zone_id_filter: [ ]



# @ignored
external-dns:
  serviceMonitor:
    # @schema
    # const: false
    # @schema
    # -- We generate ourselves the monitor
    enabled: false
  provider:
    name: cloudflare
  env:
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-key
          key: apiKey
    - name: CF_API_EMAIL
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-key
          key: email

# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false