{{ $component := "worker" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" (merge . (dict "component" $component)) }}
  labels:
    {{- include "kubee-manifest-labels" (merge . (dict "component" $component)) | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
        - name: worker
          command: [ "postal", "worker" ]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
          ports:
            - name: health
              containerPort: {{ .Values.conf_yaml.worker.default_health_server_port }}
          {{- include "postal-health-probes" . | nindent 10}}
      {{- include "postal-deploy-containers-common" . | nindent 6}}
