{{ $component := "smtp" }}
{{ $ := mergeOverwrite $ (dict "component" $component) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" . | indent 8}}
      annotations:
        checksum/secret: {{ include (print .Template.BasePath "/config/secret.yaml") . | sha256sum }}  # Checksum annotation
    spec:
      containers:
      - name: smtp
        image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
        command: ["postal", "smtp-server"]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
        ports:
        - name: smtp
          containerPort: 25
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: {{ include "postal-name-config" . }}