{{ $ := mergeOverwrite $ (dict "component" "smtp") }}
{{ $tlsComponent := "tls"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" . | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
        - name: smtp
          command: [ "postal", "smtp-server" ]
          {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
          securityContext:
            capabilities:
              add: [ "NET_BIND_SERVICE" ] # to connect to port 25
          ports:
            - name: smtp
              containerPort: {{.Values.conf_yaml.smtp_server.default_port }}
            - name: health
              containerPort: {{.Values.conf_yaml.smtp_server.default_health_server_port}}
          {{- include "postal-health-probes" . | nindent 10}}
      {{- include "postal-deploy-containers-common" . | nindent 6}}