{{ $ := mergeOverwrite $ (dict "component" "smtp") }}
{{ $tlsComponent := "tls"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" . | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" . | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
        - name: smtp
          image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
          command: [ "postal", "smtp-server" ]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
          env:
            - name: MAIN_DB_HOST
              value: '{{.Values.conf_kube.main_db.service_name}}.{{.Values.namespace}}.svc.cluster.local'
            - name: MAIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: mariadb-password
            - name: MESSAGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: mariadb-password
            - name: RAILS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "postal-name-config-secret" . }}
                  key: rails-secret-key
          ports:
            - name: smtp
              containerPort: {{.Values.conf_yaml.smtp_server.default_port }}
            - name: metrics
              containerPort: {{.Values.conf_yaml.smtp_server.default_health_server_port}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: metrics*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: metrics*/}}
          volumeMounts:
            - name: config-map
              mountPath: /config/postal.yml
              subPath: postal.yml
              readOnly: true
            - name: config-secret
              # This is the default $config-file-root/signing.key
              mountPath: /config/signing.key
              subPath: dkim-signing-key
              readOnly: true
            - name: smtp-tls
              mountPath: {{ .Values.conf_yaml.smtp_server.tls_certificate_path }}
              subPath: tls.crt
              readOnly: true
            - name: smtp-tls
              mountPath: {{ .Values.conf_yaml.smtp_server.tls_private_key_path }}
              subPath: tls.key
              readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: {{ include "postal-name-config-map" . }}
        - name: config-secret
          secret:
            secretName: '{{ include "postal-name-config-secret" . }}'
        - name: smtp-tls
          secret:
            secretName: '{{ include "postal-name-tls" . }}'