apiVersion: v1
kind: Service
metadata:
  name: {{ template "postal.fullname" . }}-smtp
  labels:
    app.kubernetes.io/name: postal
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: postal
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "postal.name" . }}
    component: smtp
  ports:
  - name: smtp
    port: 25
    targetPort: smtp
  type: {{ .Values.smtp.service.type }}
