{{ $ := mergeOverwrite $ (dict "component" "smtp") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    {{- include "kubee-pod-labels" . | indent 6}}
  ports:
  - name: smtp
    port: 25
    targetPort: smtp

