{{ $ := mergeOverwrite $ (dict "component" "smtp") }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.conf_kube.smtp_server.service_name}}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
spec:
  selector:
    {{- include "kubee-pod-labels" . | indent 4}}
  ports:
    - name: smtp
      port: {{.Values.conf_kube.smtp_server.service_port}}
      targetPort: smtp

