{{/*
   Doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22
  Chart: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#ingress-configuration
*/}}
{{- if ne ( ((.Values.kube_x).argocd).hostname) "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
{{/*  namespace: {{ .Values.kube_x.argocd.namespace }}*/}}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kube_x.cert_manager.defaultIssuerName }}'
    {{- end }}
    {{- /* Only from Github or our network */}}
    {{- if and (not (empty (((.Values.kube_x).cluster).private_networks))) ( eq .Values.kube_x.argocd.git.webhook.service "github") }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.kube_x.traefik.namespace }}-{{ include "kube-x-traefik-github-hooks-allow-list-name" . }}@kubernetescrd
    {{- end}}
spec:
  ingressClassName: traefik
  rules:
    - host: '{{ .Values.kube_x.argocd.hostname }}'
      http:
        paths:
          - backend:
              service:
                name: 'argocd-server'
                port:
                  number: 443
            path: /
            pathType: Prefix
  {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
  tls:
    - hosts:
        - '{{ .Values.kube_x.argocd.hostname }}'
      secretName: 'argocd-cert'
  {{- end }}
{{- end -}}


