{{- /*
  # Email Notification User and Password
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/#getting-started
*/}}
{{- if ne .Values.kube_x.email.smtp.host "" }}
{{- if (eq .Values.secret.kind "ExternalSecret") -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: {{ template "kube-x-argocd-notifications-secret-name" }}
  namespace: {{ .Values.namespace }}
spec:
  # The store from where
  secretStoreRef:
    name: {{ .Values.kube_x.external_secrets.store.name }}
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: {{ template "kube-x-argocd-notifications-secret-name" }} # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Email Credentials for notifications"
  # Mapping to local secret from remote secret
  data:
    - secretKey: {{ template "kube-x-argocd-email-username-variable-name" }} # Prop Name in the kubernetes secret
      remoteRef:
        key: email # Name of the remote secret
        property: {{ template "kube-x-argocd-email-username-variable-name" }} # Prop Name in the remote secret
    - secretKey: {{ template "kube-x-argocd-email-password-variable-name" }} # Prop Name in the kubernetes secret
      remoteRef:
        key: email # Name of the remote secret
        property: {{ template "kube-x-argocd-email-password-variable-name" }} # Prop Name in the remote secret
{{- end -}}
{{- end -}}