apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    # select all ServiceMonitors with the `team: frontend` label.
    # It enables the frontend team to create new `ServiceMonitors` and `Services`
    # without having to reconfigure the Prometheus object.
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 200Mi
  enableAdminAPI: false
