# Enable/Disable
enabled: false

# Namespace
namespace: 'mail'

# Hostname
hostname: ''

# Mail Pit Values
mailpit:
  image:
    # https://github.com/axllent/mailpit/releases
    tag: "v1.22.3"
  service:
    smtp:
      port: 465
      #externalTrafficPolicy: Local
  args:
    # https://mailpit.axllent.org/docs/configuration/smtp/#smtp-with-ssltls
    - '--smtp-require-tls'
  mailpit:
    smtp:
      tls:
        enabled: true
        secretName: "mailpit-cert"

# Don't change, don't touch
# Used to not output template from cross dependency in Chart.yaml
kubee_internal:
  install_cross_dependency: false