# yaml-language-server: $schema=values.schema.json

# @schema
# title: Enabled
# type: boolean
# required: true
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation Namespace
namespace: 'mail'

# @schema
# title: Hostname
# description: The hostname
# required: true
# minLength: 1
# @schema
# -- The hostname
hostname: ''

# @schema
# title: Private Network Restriction
# description: Applied the private network middleware
# required: true
# type: boolean
# @schema
# Enable private network
# If true and a private network has been defined in Traefik,
# only the IP from the private network will be able to
# connect to the SMTP server
enable_private_network_middleware: true

# Mail Pit Values
mailpit: # @schema hidden: true; $ref: https://raw.githubusercontent.com/jouve/charts/refs/heads/main/charts/mailpit/values.schema.json
  image:
    # https://github.com/axllent/mailpit/releases
    tag: "v1.22.3"
  service:
    smtp:
      port: 465
      #externalTrafficPolicy: Local
  args:
    # https://mailpit.axllent.org/docs/configuration/smtp/#smtp-with-ssltls
    - '--smtp-require-tls'
  mailpit:
    smtp:
      tls:
        enabled: true
        secretName: "mailpit-cert"


# Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false