#!/usr/bin/env bash

# This script update the version and appversion of the chart

source bashlib-error.sh
error::set_strict_mode
error::set_trap
source bashlib-echo.sh

# this works for executed script or sourced script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

CHART_PATH="$SCRIPT_DIR/Chart.yaml"
# Get the Traefik chart
TRAEFIK_CHART_VERSION=$(yq '.dependencies[] | select(.name == "traefik") | .version' "$CHART_PATH" | tr -d '~' )

if [ "$TRAEFIK_CHART_VERSION" == "" ]; then
  echo::err "Unable to retrieve the traefik chart version (the value was empty)"
  exit 1
fi
echo::info "Updating traefik-crds for the Traefik chart $TRAEFIK_CHART_VERSION"

TRAEFIK_VERSION=$(curl -s https://traefik.github.io/charts/index.yaml | yq ".entries.traefik[] | select(.version == \"$TRAEFIK_CHART_VERSION\") | .appVersion")
if [ "$TRAEFIK_VERSION" == "" ]; then
  echo::err "Unable to retrieve the traefik version from the repo (the value was empty)"
  exit 1
fi


echo::info "Updating traefik Chart.yml with appVersion $TRAEFIK_VERSION"
yq ".appVersion = \"$TRAEFIK_VERSION\"" -i "$CHART_PATH"
yq ".version = \"$TRAEFIK_CHART_VERSION\"" -i "$CHART_PATH"
yq ".version = \"$TRAEFIK_CHART_VERSION\"" -i "$CHART_PATH"
