apiVersion: v1
kind: Secret
metadata:
  name: mariadb-init
type: Opaque
stringData:
  init-sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    CREATE USER 'myuser'@'%' IDENTIFIED BY 'myuser-password';
    GRANT ALL PRIVILEGES ON mydb.* TO 'myuser'@'%';
    FLUSH PRIVILEGES;


