apiVersion: v1
kind: Secret
metadata:
  name: postal-mariadb-init-kubee
type: Opaque
stringData:
  # Maria db User prerequisites
  # If you are unable or unwilling to grant root access, the database user you create separately needs all permissions on databases called postal and postal-*
  # (this prefix can be configured in the message_db part of your configuration).
  # https://docs.postalserver.io/getting-started/prerequisites#mariadb-106-or-higher
  01-init.sql: |
    GRANT ALL PRIVILEGES ON `{{.Values.conf_yaml.message_db.database_name_prefix}}%`.* TO '{{.Values.conf_yaml.main_db.username}}'@'%' WITH GRANT OPTION;


