apiVersion: v1
kind: Service
metadata:
  name: {{.Values.conf_kube.main_db.service_name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{.Values.conf_yaml.main_db.port}}
      targetPort: {{.Values.conf_yaml.main_db.port}}
  type: ClusterIP