# A service for both internal use and for the Ingress.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dex-service-name" }}
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: dex
spec:
  ports:
    - port: 5556
  selector:
    app.kubernetes.io/name: dex