---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - name: keycloak
          image: "quay.io/keycloak/keycloak:{{ .Values.version }}"
          args: ["start", "--cache-stack=kubernetes"]
          env:
            # Bootstrap user
            # https://www.keycloak.org/server/configuration#_creating_the_initial_admin_user
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "{{ .Values.kubee.auth.admin_user.username }}"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "{{ .Values.kubee.auth.admin_user.password }}"
            - name: KC_PROXY
              value: "edge"
            # Enable health and metrics support
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            # Db
            - name: KC_DB
              value: ""
          ports:
            - name: https
              containerPort: 8443
            - name: jgroups
              containerPort: 7600
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
