apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: '{{ .Values.kube_x.templates.globalPrefix }}-ip-allow-github-hooks-cidr'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    description: This middleware allows only the GitHub Hooks CIDR and our private network
spec:
  # https://doc.traefik.io/traefik/v3.0/middlewares/http/ipallowlist/
  ipAllowList:
    sourceRange:
      - 192.30.252.0/22
      - 185.199.108.0/22
      - 140.82.112.0/20
      - 143.55.64.0/20
      - 143.176.206.82/32