{{/*
The certifiate that valid kube-x.dev and *.kube-x.dev
domain
Used as default cert
https://doc.traefik.io/traefik/https/tls/#default-certificate
Certificate was made with mkcert.
export CAROOT=resources/cluster/apps/traefik/mkcert
mkcert "kube-x.dev" "*.kube-x.dev"
*/}}
{{- if eq (((.Values.kube_x).traefik).enabled) false -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "traefik-name-prefix" . }}-kube-x-dev-certificate'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: traefik
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVKRENDQW95Z0F3SUJBZ0lRY0RtcmJYT2x6RE12TXltQ0ZFSm9aREFOQmdrcWhraUc5dzBCQVFzRkFEQmwKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhIVEFiQmdOVkJBc01GR0ZrYldsdQpRRTFKVGtrdFRrbERUeTVPU1VOUE1TUXdJZ1lEVlFRRERCdHRhMk5sY25RZ1lXUnRhVzVBVFVsT1NTMU9TVU5QCkxrNUpRMDh3SGhjTk1qUXhNakV5TWpJME1qTTFXaGNOTWpjd016RXlNakkwTWpNMVdqQklNU2N3SlFZRFZRUUsKRXg1dGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1kyVnlkR2xtYVdOaGRHVXhIVEFiQmdOVkJBc01GR0ZrYldsdQpRRTFKVGtrdFRrbERUeTVPU1VOUE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnV3RWh0ejNvaFgyQ1BlVnZvakV1REtrTWppS2c0c1F0ekxqdHVsM0ZZRXZxWlZZR0t2NE0xTmhKVDFnUk1rRTUKcE5CYXBSLy9KQ2lWVjNUZm10Q29mK0VwbzdxcXQ0dHdOWlM5UzQxdC8wL212NU9kNW1FM3BRanhmNms3Q3pZdgpyeUpOdnp6MDJkb052YXF0NXl3OHpUQUlvL2VURzc5d0RrV0NXalNLbEp6UThsT3FjM2JEWVJmRnVCMlE2OUpDCnV0Q1pVblJaY0JndnhFWGRqc3MzeGVhcnh1QTllN0Y1TVR6UnRiMzlsQ3phMnB0LzFKS1duYUFOYUdEdVp1VVMKd201U0xhbHM2OEF5dmF5SFhSMTR1b3NyQnQ2VTkxeCtDTEdGdENUWWVSRlpFWGwyY0lSWkpZUzF4RFZmRkI2SwpjWVB4STN0VEw0amh2QlhiQlJpRDJRSURBUUFCbzIwd2F6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsCkJBd3dDZ1lJS3dZQkJRVUhBd0V3SHdZRFZSMGpCQmd3Rm9BVTVzdVM4OERsYzVNK0s3RHVmL1JxOGFEL3cvMHcKSXdZRFZSMFJCQnd3R29JTUtpNXJkV0psTFhndVpHVjJnZ3ByZFdKbExYZ3VaR1YyTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQmdRQUlzOC9iTk9EdVdrajR4eFFDVEFKWFNtSWxUT2Y4L3B1ZUVRR0VMcklQUVhFSE1yWGRFV0VRCnJrajQvZ0szS1h4clFKOUdndGdJOTZnU0xML29rZ3hvUVNHSkgwSU05Z2hCeFZxN1pQRXp4WExYZVkxaGNRWGEKbjhJaWk1YTA0YWx2VEZMdnk0WkZ1Q
    VpnM2VzRmVYZC96bXpFTnFOMk1wU0d0ejZCa0FoanE1L0xhbjFJemNFKwp1b0JaZzZwNFpwaVFHT1BCZEk5VE9XQkNhSzl6SUZJTTh4U2FxenlvK2NnWWpDUjJ1VytMb2lDMTRBTnhVRkZjCk5SYXdDbTV5OGk1ZnVDSmJSblR0QUVMZDZmNk01Z29zU3NQcVVVcjhLWlhQWXE4UHVhQXB0ckd1UVREWnJnWmsKKzN4d25UNW4rN
    3ppMzhleU1WcXY3VmZUcEZnYlFUUm1FaE44aFVESkJUQU4ySzJadW4rUi9OTDliTVFiZTdhUApkL3NQT2l0MEkrTWpXbUsyOXdaaWNoTVpNVkVXU00wWmlkNWM2bGJBc1hIQnQreTRXb1pjdjFlRndjQTZyOUlkCkVRNEplazI4VzhoVittNEk4aXhMTXM0RlhYQTc0cVcrUzUzN2tHZ2lRSzd3M2JOZW0wdWZJNWhjSzc3MkVCU24KcTZyYmdTbFFDR0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzdBU0czUGVpRmZZSTkKNVcraU1TNE1xUXlPSXFEaXhDM011TzI2WGNWZ1MrcGxWZ1lxL2d6VTJFbFBXQkV5UVRtazBGcWxILzhrS0pWWApkTithMEtoLzRTbWp1cXEza
    TNBMWxMMUxqVzMvVCthL2s1M21ZVGVsQ1BGL3FUc0xOaSt2SWsyL1BQVFoyZzI5CnFxM25MRHpOTUFpajk1TWJ2M0FPUllKYU5JcVVuTkR5VTZwemRzTmhGOFc0SFpEcjBrSzYwSmxTZEZsd0dDL0UKUmQyT3l6ZkY1cXZHNEQxN3NYa3hQTkcxdmYyVUxOcmFtMy9Va3BhZG9BMW9ZTzVtNVJMQ2JsSXRxV3pyd0RLOQpySWRkS
    FhpNml5c0czcFQzWEg0SXNZVzBKTmg1RVZrUmVYWndoRmtsaExYRU5WOFVIb3B4Zy9FamUxTXZpT0c4CkZkc0ZHSVBaQWdNQkFBRUNnZ0VBU3JKZkIxVGhSa0VsL3hkZ2lnYmZBQXVlaWovbXgrM1k1WWVRM2ZxSzFyWTgKUUpJbUVKSStDZDhER1lCeURnTGp4YU84TVcwZ2V3OEM2RlkwNHlBcHpqcmdhUmd0RFBmVHNITmpVW
    VNDeFpMaQo5dTgrQ1VJWCtnSWloUDNTS2Q1UkdjRzRFSVdHd0daTFN0R2NlVlRBVEsyOUpkSEVuemJPeWNTV0Z2WVp6TlpQCnVLclpMdzFFaUc2N2pPemM3aVVzaVNaU1JYT2RmdWh5MjVwNjBDTWZCS203S0VhcTMwenovR3dxbXhOU2sxMEoKN2tyak56TU41ZGhkTmFORlc1RklRUEFGcVlKaTNGamR6OEgwWERwSGUvaXVCS
    WtqMVlsaldsQzBOMWh2d2lwaworTEhsaXdTR3U5UElhbWtFNkxlOWtmRldEcnBNRU04S0E4d3QzT0ppU1FLQmdRRE4xR29IWlRib3FmRVVNMXowCk8wQTJUVzQ4dEt3QUZDMk8yMjZlYW1HaHF4SW94YVY2MjF6U1pTQk1aeVJJUjh0Um8xWURVYVp0dll3Z2hkZksKTGY3OUJaMWdCYUNOZFlEdWM5K2ZXeXpScTBFMTFFR25Fc
    jJCQzAvNGhiVXlwVEdSNDJQRHQwNHAvRDZDZTJ4cAowK2haYXA3cC9qdm1qV2x6ZEt6TGdkNVdHd0tCZ1FEb2xnanBpNDVFb0l4K3Y0OTdsa2h4ajRaYTI3bW14Qi9QClpqeDZGZEtRaUdPVlQ3Z1pUemxCMThsS0puZWZEY0k5V3ZvaDlJUGREdURvSE5XcDcxVlZ1d09kcXl4ZUozTHcKUWw3Wmwxd3EvNC8xRzRyVmlVVjE4U
    jRNMjdLYTNua3AzSENCYUdWSWhtZ0RzbUxvcldaaGIrVVdLbTFnL0RleAoyRllYbm5NOUd3S0JnRDJpc3hGOTNLQjFhMHk2U01hV0M1ZDNQbUNOVmNnOFFwdzUxM2syci8vQ2c1Q1VCd2F3Ck02NkpPOC9GUHhjcDhKZUV5dGY1bGxYY1lkN0hWYVFrZSt2MngzYWVtTUpqZ25WbFczeVR4K3NOVmx5eEwrdkEKNytCNXE3dm5Ca
    WloVVNPM3JRTkptKzEwcko5VUtGWFVjQXArcEJHNzRPSWNUSXlYVHJzdUs0OHJBb0dCQUozWQpmUEhxeVVHZjU5bDVMZXBFNHFOWE1XcG1Ka2VjWUs1RGh4V2Z5OGhWRjZoVWN1K1NTWng2MHR2azRWZnJZWUI4ClJyZFdsMHNsOXRMd0JyMk9kTTU2M2doYURBRldLbllOeFF0TTRyczN0NzR6MC9QNWRrK0Z0TXdyS2JwYTg4W
    EsKR2Z4cEdodXZROVlHY1lQUmNtTDhLbS94bVV1eHdDYU5XRmd0SzY0ekFvR0FIM1UreWM5U2VHSjNrZ094eW1ZbApEcHE5ZUJDREoxZGVSOFE5OG5INFhKekhGcCtiSHJmclJaQ2lKZ0pXMFE2bGR6LzkralRRVkJWMmRTSVVicW5pCkU5TkJNL2FWcXRITWhobVh5QTRmSEZMc1E0SzdBWXBibkZJbUJQZ3hWUmt3a2pZeGFobXpiSHZsVGVSRFJJZVkKeTFOU2E1WmVVOEdRT2VmUjlVclFDVWc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: '{{ .Release.Namespace }}'
spec:
  defaultCertificate:
    secretName: '{{ include "traefik-name-prefix" . }}-kube-x-dev-certificate'
{{- end }}