{{/*

Test:
helm template -s templates/secret-grafana-cloud.yaml \
  --set 'kube_x.grafana.target=external'  \
  --set 'kube_x.grafana.apiToken=xxxx'  \
  . | yq

*/}}
{{- if ne $.Values.kube_x.grafana.apiToken "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "grafana-instance-api-token-secret-name" . }}'
  namespace: '{{.Release.Namespace}}'
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
   {{ template "grafana-instance-api-token-secret-key" }}: {{ $.Values.kube_x.grafana.apiToken | b64enc }}
{{- end}}
