{{/*
  Grafana Instance (Cloud (External) or Cluster (Internal)
  See CRD doc:   https://grafana.github.io/grafana-operator/docs/grafana/
*/}}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.name }}
  namespace: '{{ .Values.namespace }}'
  labels:
    {{/*
      Label used to apply Grafana CRD to this instance (ie which Grafana instance a CRD dashboard, ... resource applies to)
      https://grafana.github.io/grafana-operator/docs/overview/#instanceselector
    */}}
    dashboards: {{ required "name is required" .Values.name }}
spec:
{{/*
Create a external instance (cloud)
Doc: https://grafana.github.io/grafana-operator/docs/grafana/#external-grafana-instances
Example: https://grafana.github.io/grafana-operator/docs/examples/external_grafana/readme/
Grafana Cloud: https://grafana.com/docs/grafana-cloud/developer-resources/infrastructure-as-code/grafana-operator/manage-dashboards-argocd/

Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'type=external'  \
    --set 'api_token=xxxx'  \
    --set 'hostname=stackName.grafana.net'  \
    --set 'prometheus.enabled=true'  \
    . | yq

*/}}
{{- if eq ( required "type is required" .Values.type) "external" -}}
  external:
    url: https://{{ .Values.hostname }}/
    apiKey:
      name: '{{ template "grafana-instance-api-token-secret-name" . }}'
      key: '{{ template "grafana-instance-api-token-secret-key" . }}'
{{/*
  Create a cluster local instance
  https://grafana.github.io/grafana-operator/docs/quick-start/#creating-a-grafana-instance

  Test:
  helm template -s templates/grafana-instance.yaml \
    --set 'type=internal'  \
    --set 'hostname=grafana.bar.com'  \
    --set 'cert_manager.enabled=true'  \
    --set 'prometheus.enabled=true'  \
    --set 'kube_x.auth.admin_user.username=xxxx'  \
    --set 'kube_x.auth.admin_user.password=xxxx'  \
    --set 'kube_x.auth.admin_user.email=xxxx'  \
    . | yq
*/}}
{{- else -}}
  {{/*
    Ingress is defined as Yaml values.
    https://grafana.github.io/grafana-operator/docs/examples/ingress_https/readme/
    Nonte: it seems that they use the Helm Chart ???
    https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml
   */}}
  {{- if ne .Values.hostname "" }}
  ingress:
    metadata:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        {{- if ne .Values.cert_manager.enabled false }}
        cert-manager.io/cluster-issuer: '{{ .Values.cert_manager.issuer_name }}'
        {{- end }}
    spec:
      ingressClassName: traefik
      rules:
        - host: '{{ .Values.hostname }}'
          http:
            paths:
              - backend:
                  service:
                    name: '{{ .Values.name }}-service'
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      {{- if ne .Values.cert_manager.enabled false }}
      tls:
        - hosts:
            - '{{ .Values.hostname }}'
          secretName: '{{ include "grafana-name" . }}'
      {{- end }}
  {{- end -}}
  {{/*
      Config Doc
      https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
  */}}
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: {{ required "kube_x.auth.admin_user.username is required for a local grafana instance" .Values.kube_x.auth.admin_user.username }}
      admin_password: {{ required "kube_x.auth.admin_user.password is required for a local grafana instance" .Values.kube_x.auth.admin_user.password }}
      admin_email: {{ required "kube_x.auth.admin_user.email is required for a local grafana instance" .Values.kube_x.auth.admin_user.email }}
{{- end -}}