# Service for Traefik to talk to Forward-Auth.
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - port: {{ template "traefik-forward-auth-port" }}
