# Common Kubee values used in sub-charts
kubee:
  # Cluster Wide Variables
  cluster:
    # The admin user of the cluster
    adminUser:
      username: "admin"
      password: "${KUBEE_CLUSTER_ADMIN_PASSWORD}"
      email: "foo@bar.com"
  # Kubee Prometheus
  prometheus:
    # Not a string, a boolean so no quote
    enabled: false
  # Kubee Dashboard Variables
  kubernetes_dashboard:
    # The external DNS
    hostname: 'dash.kubee.dev'
  # Whoami
  whoami:
    hostname: 'whoami.kubee.dev'
  # Kubee Traefik Variables
  traefik:
    defaultCertificate:
      # The PEM content file
      # Not a path to the cert file relatif to the working directory (ie cluster directory)
      # Set with `KUBEE_HELM_INSTALL_OPTIONS`
      # --set-file kubee.traefik.defaultCertificate.cert=cert/kubee.dev+1.pem
      cert: ''
      # The PEM content file
      # Not a path to the key file relatif to the working directory (ie cluster directory)
      # Set with `KUBEE_HELM_INSTALL_OPTIONS`
      # --set-file kubee.traefik.defaultCertificate.key=cert/kubee.dev+1-key.pem
      key: ''
    dashboard:
      # The FQDN for the traefik dashboard
      hostname: 'traefik.kubee.dev'

# Traefik Values
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
traefik:
  # Traefik experimental features
  experimental:
    # Equivalent to the cli flag (passed in additionalArguments)
    # - `--experimental.plugins.sablier.modulename=github.com/acouvreur/sablier'
    # - `--experimental.plugins.sablier.version=v1.7.0'
    plugins:
      sablier:
        moduleName: github.com/acouvreur/sablier
        version: v1.7.0

  additionalArguments:
    # Debug
    - '--log.level=DEBUG'
    # Logs just add too much noise on what is going on
    - '--accesslog=true'
