kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postal-name-config-secret" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  mariadb-password: {{ .Values.conf_secrets.db_password | b64enc | quote }}
  dkim-signing-key: {{ .Values.conf_secrets.dkim_signing_key | b64enc | quote }}
  rails-secret-key: {{ .Values.conf_secrets.rails_secret_key | b64enc | quote }}
  smtp-password: {{ .Values.conf_secrets.smtp_password | b64enc | quote }}
