apiVersion: v2
name: kubee-kuberhealthy
description: Kubee Kuberhealthy Chart
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.8.0-rc2" # Kuberhealthy Operator version used in the README to get the values.yaml

annotations:
  app.kubernetes.io/name: "kuberhealthy"
  artifacthub.io/operator: "true"
  chart.kubee/status: "stable"
  chart.kubee/kind: "app"
  chart.kubee/category: "test"
  chart.kubee/engines: |
    - helm
  chart.kubee/crds: |
    - name: kubee-kuberhealthy-crds
      version: 2.8.0-rc2
      repository: file://../kuberhealthy-crds


dependencies:
  # ie https://github.com/grafana/grafana-operator/pkgs/container/helm-charts%2Fgrafana-operator
  # https://github.com/grafana/grafana-operator/releases
  - name: kuberhealthy
    version: '104' # Should not be possible but it's.
    repository: https://kuberhealthy.github.io/kuberhealthy/helm-repos
    #condition: xxx.enabled
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
  - name: kubee-cert-manager
    version: 0.0.1
    repository: file://../cert-manager
    alias: cert_manager
    condition: kubee_internal.install_cross_dependency
  - name: kubee-traefik
    version: 0.0.1
    repository: file://../traefik
    alias: traefik
    condition: kubee_internal.install_cross_dependency
  - name: kubee-grafana
    version: 0.0.1
    repository: file://../grafana
    alias: grafana
    condition: kubee_internal.install_cross_dependency
