apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
# noinspection KubernetesMissingKeys
spec:
  template:
    spec:
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              memory: {{ .Values.components.argocd_application_controller.resources.memory }}
            limits:
              memory: {{ .Values.components.argocd_application_controller.resources.memory }}
