# Email Notification User and Password
# https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/#getting-started
{{- if ne .Values.kube_x.cluster.email.smtp.host "" }}
{{- if (eq .Values.kube_x.cluster.secret "Secret") -}}
{{/*

Test:
helm template -s templates/argocd-notifications-secret.yml \
  --set 'kube_x.cluster.email.smtp.host=smtp.gmail.com'  \
  --set 'kube_x.cluster.email.smtp.port=587'  \
  --set 'kube_x.cluster.email.smtp.username=nico'  \
  --set 'kube_x.cluster.email.smtp.password=welcome'  \
  --set 'kube_x.cluster.adminUser.email=foo@gmail.com' \
  . | yq

*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-x-argocd-notifications-secret-name" }}
{{/*  namespace: {{ .Values.kube_x.argocd.namespace }}*/}}
  annotations:
    kustomize.config.k8s.io/behavior: merge
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
  {{ template "kube-x-argocd-email-username-variable-name" }}: {{ required ".Values.kube_x.cluster.email.smtp.username is required" .Values.kube_x.cluster.email.smtp.username | b64enc}}
  {{ template "kube-x-argocd-email-password-variable-name" }}: {{ required ".Values.kube_x.cluster.email.smtp.password is required" .Values.kube_x.cluster.email.smtp.password | b64enc}}
{{- end -}}
{{- end -}}