# TLS certificate for the Dex service, from local certificate authority.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "oauth2-proxy-cert-local-name" . }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ include "oauth2-proxy-cert-local-name" . }}
  issuerRef:
    kind: Issuer
    name: {{ include "kubee-name-prefix" . }}-ca
  dnsNames:
    - {{ include "oauth2-proxy-service-name" . }}
    - {{ include "oauth2-proxy-service-name" . }}.{{ .Values.namespace }}
    - {{ include "oauth2-proxy-service-name" . }}.{{ .Values.namespace }}.svc.cluster.local
