# TLS certificate for the Dex service, from local certificate authority.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubee-name-prefix" . }}-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ include "kubee-name-prefix" . }}-tls-ca
  issuerRef:
    kind: Issuer
    name: {{ include "kubee-name-prefix" . }}-ca
  dnsNames:
    - oauth2-proxy
    - oauth2-proxy.{{ .Values.namespace }}
    - oauth2-proxy.{{ .Values.namespace }}.svc.cluster.local
