apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy-service-name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: {{ include "oauth2-proxy-metrics-port" .}}
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
