---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: oauth2-proxy
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{(index .Values "oauth2-proxy").config.existingSecret}}
  namespace: {{.Values.namespace}}
type: Opaque
data:
  # This data are mounted as env in the deployment
  cookie-secret: {{ tpl (required "oauth2_proxy.auth.cookie_secret is required"  .Values.auth.cookie_secret) $ | b64enc | quote }}
  client-secret: {{ tpl (required "dex.clients.oauth2_proxy.secret is required" .Values.dex.clients.oauth2_proxy.secret) $ | b64enc | quote }}
  client-id: {{ tpl (required "dex.clients.oauth2_proxy.client_id is required" .Values.dex.clients.oauth2_proxy.client_id) $ | b64enc | quote }}

