{{- range .Values.project_uuids }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: healthchecks
spec:
  jobName: healthchecks
  scrapeInterval: 60s
  scheme: HTTPS
  metricsPath: /projects/{{ . }}/metrics/{{ required "read_only_api_key is required" $.Values.read_only_api_key }}
  staticConfigs:
    - targets:
        - healthchecks.io
{{- end }}