# Git repository are created with a secret and configuration
# https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repositories-yaml/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: argocd-secret-repo
spec:
  # The store from where
  secretStoreRef:
    name: kube-x-external-secret-store-vault
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: repo-base # Secret name in Kubernetes
    template:
      data:
        # .git is mandatory
        url: 'https://github.com/gerardnico/kube-argocd.git'
        username: 'whatever'
        password: "{{ .password }}"
        # insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
        # forceHttpBasicAuth: "true" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
        # enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
        annotations:
          description: "The Secret defines the Git repository connection properties"
  # Mapping to local secret from remote secret
  data:
    - secretKey: password # Prop Name in the secret
      remoteRef:
        key: argocd # Name of the remote secret
        property: github-token # Prop Name in the remote secret


