# yaml-language-server: $schema=values.schema.json

# @schema
# title: Enabled
# type: boolean
# required: true
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation Namespace
namespace: 'mail'

# @schema
# title: Hostname
# description: The hostname
# required: true
# minLength: 1
# format: hostname
# @schema
# -- The hostname
hostname: ''

# @schema
# title: Version
# description: The postal version
# required: true
# @schema
# -- The postal version, https://github.com/postalserver/postal/releases
version: 'v3.3.4'

# @schema
# title: Signing Private Key
# description: The signing key
# required: true
# minLength: 5
# @schema
# -- Private key (for signing payload)
# It should be in pem format (BEGIN/END PRIVATE KEY)
signing_key: ''

# @schema
# title: Components
# description: The components
# @schema
components:
  smtp:
    resource:
      memory: ''
      cpu: ''
  web:
    resource:
      memory: ''
      cpu: ''
  worker:
    resource:
      memory: ''
      cpu: ''


# dependencies
# check available values here: https://artifacthub.io/packages/helm/bitnami/mariadb?modal=values-schema
# @ignored
mariadb:

  # -- set it to false if you want to use [operator](https://github.com/mariadb-operator/mariadb-operator/)
  enabled: true
  # TODO: we should switch to templating for the name to avoid using reference to fullname override everywhere
  fullnameOverride: postal-mariadb
  auth:
    database: "postal"
    username: "postal"
    # @schema
    # title: Database Password
    # description: The database password
    # required: true
    # minLength: 5
    # @schema
    password: ""
  initdbScripts:
    # NOTE: postal is creating postal-server-* databases to handle postal mail servers configuration
    grant_privileges.sql: |
      GRANT ALL PRIVILEGES ON `{{ .Values.mariadb.auth.database }}%`.* TO '{{ .Values.mariadb.auth.username }}'@'%' WITH GRANT OPTION;

# Internal Kubee constant
# @ignored
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false