
# Cluster Wide Variables
cluster:
  auth:
    # The admin user of the cluster
    admin_user:
      username: "admin"
      password: "${KUBEE_CLUSTER_ADMIN_PASSWORD}"
      email: "admin@example.com"
    private_networks:
      - '143.176.207.82/32'
  # Default email
  email:
    smtp:
      host: 'smtp.gmail.com'
      port: '587'
      from: 'admin@example.com'
      username: 'admin@example.com'
      password: "${KUBEE_CLUSTER_EMAIL_SMTP_PASSWORD}"

# Kubee Dashboard Variables
kubernetes_dashboard:
  # The external DNS
  hostname: 'kube-xxx.nip.io'
# Whoami
whoami:
  hostname: 'whoami-xxx.nip.io'
# Kubee Traefik Variables
traefik:
  default_certificate:
    # The PEM content file
    # Not a path to the cert file relative to the working directory (ie cluster directory)
    # Set with `KUBEE_HELM_INSTALL_OPTIONS`
    # --set-file traefik.default_certificate.cert=cert/kubee.dev+1.pem
    cert: ''
    # The PEM content file
    # Not a path to the key file relative to the working directory (ie cluster directory)
    # Set with `KUBEE_HELM_INSTALL_OPTIONS`
    # --set-file traefik.default_certificate.key=cert/kubee.dev+1-key.pem
    key: ''
  # The FQDN for the traefik dashboard
  hostname: 'traefik-xxx.nip.io'
  # Helm Traefik Chart Values
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  traefik:
    additionalArguments:
    # Debug
    # - '--log.level=DEBUG'
    # Logs just add too much noise on what is going on
    # - '--accesslog=false'
# Cert Manager
cert_manager:

  # This is the kubee template condition used to create certificate for ingress route
  # when disabled, the default traefik certificate is used
  enabled: true

  # The issuer used in all certificate request of kubee.
  issuer_name: 'letsencrypt-prod'

  # Dns01 challenge
  dns01:
    cloudflare:
      # See cert-manager/README.md on how to get cloudflare api key
      # A secret or external secret can be created
      secret:
        # A Kubernetes secret will be created if not empty
        cloudflareApiToken: '${KUBEE_CERT_MANAGER_API_TOKEN}'
      # The dns Zones that are managed by cloudflare, mandatory
      dnsZones:
        - example.com
        - foo.com
        - bar.com

# Kubee Prometheus
prometheus:
  # Not a string, a boolean so no quote
  enabled: true
# Grafana
grafana:
  enabled: true
  hostname: grafana-xxx.nip.io

# External Secrets for Gitops
external_secrets:
  enabled: true
  store:
    name: 'vault-external-secret-store'
    vault:
      apiToken: '${KUBEE_EXTERNAL_SECRETS_VAULT_API_TOKEN}'

# Argo Cd for Gitops
argocd:
  hostname: 'argocd-xxx.nip.io'
  git:
    repo:
      url: 'https://github.com/org/repo.git'
      username: 'whatever'
      password: '${KUBEE_ARGOCD_GITHUB_TOKEN}'
    webhook:
      service: 'github'
      secret: '${KUBEE_ARGOCD_WEBHOOK_SECRET}'

