apiVersion: v2
name: kubee-cert-manager
description: The Cert Manager Kubee Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# The version of cert manager and trust manager
# Should be the same in CRD Chart
appVersion: "v1.17.1-v0.16.0"

annotations:
  app.kubernetes.io/name: "cert-manager"

# https://github.com/cert-manager/cert-manager/releases
# https://cert-manager.io/docs/installation/helm/#example-usage
dependencies:
  - name: cert-manager
    version: v1.17.1
    repository: https://charts.jetstack.io
  # Release https://github.com/cert-manager/trust-manager/releases
  - name: trust-manager
    version: v0.16.0
    repository: https://charts.jetstack.io
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  # For the dashboard
  - name: kubee-grafana
    version: 0.0.1
    repository: file://../grafana
    alias: grafana
    condition: kubee_internal.install_cross_dependency
  # For the scrape
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
