# Installation
# Ref: https://github.com/argoproj/argoproj-deployments/blob/master/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Custom Namespace
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#installing-argo-cd-in-a-custom-namespace
namespace: ${KUBE_X_NAMESPACE}

patches:
  # Patch needed to apply the server transport via annotation to disable tls validation from Traefik
  - path: templates/patches/argocd-application-controller.yaml
  - path: templates/patches/argocd-cmd-params-cm.yaml
  - path: templates/patches/argocd-notifications-cm.yaml
  - path: templates/patches/argocd-notifications-secret-patch.yaml
  - path: templates/patches/argocd-secret-patch.yaml
  - path: templates/patches/argocd-svc-no-tls-patch.yaml
  # CustomNamespace patch: https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#installing-argo-cd-in-a-custom-namespace
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: ${KUBE_X_NAMESPACE}
    target:
      kind: ClusterRoleBinding

# Note: External Secret are resources while secret already present in install.yaml are patches
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.3/manifests/install.yaml
  - templates/resources/argocd-ingress.yaml
  - templates/resources/argocd-namespace.yaml
  - templates/resources/argocd-notifications-secret-external.yaml
  - templates/resources/argocd-secret-external.yaml
  - templates/resources/argocd-secret-repo.yaml
  - templates/resources/argocd-service-monitors.yaml
  - templates/resources/argocd-svc-no-tls-transport.yaml
