# Installation
# Ref: https://github.com/argoproj/argoproj-deployments/blob/master/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  # patch needed to apply the server transport via annotation to disable tls validation from Traefik
  - path: patches/argocd-svc-no-tls-patch.yml
  # Notification Configuration
  - path: templates/argocd-notifications-config-map-patch.yml
  # Command line argument
  - path: templates/argocd-cmd-params-cm.yml

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml
#  # Namespace
#  - templates/argocd-namespace.yml
#  # Ingress taken by Traefik
#  - templates/argocd-ingress.yml
#  # Secrets
#  - templates/argocd-secret-repo.yml
#  - templates/argocd-secret.yml
#  - templates/argocd-notifications-secret.yml
#  # Traefik Server transport to disable tls verify
#  - templates/argocd-svc-no-tls-transport.yml
#  # Metrics
#  - templates/argocd-service-monitor-metrics.yml
#  - templates/argocd-prometheus-alert-rule.yml

