# Installation
# Ref: https://github.com/argoproj/argoproj-deployments/blob/master/argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Custom Namespace
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#installing-argo-cd-in-a-custom-namespace
namespace: argocd

patches:
  # Patch needed to apply the server transport via annotation to disable tls validation from Traefik
  - path: patches/argocd-svc-no-tls-patch.yml
  # CustomNamespace patch: https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#installing-argo-cd-in-a-custom-namespace
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml
