
# Namespace
# https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#installing-argo-cd-in-a-custom-namespace
namespace: 'argocd'
# The argocd hostname
# if not empty, an ingress is created
hostname: ''
# Git
git:
  # Repo
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repositories-yaml/
  repo:
    # The repo URL
    # !!! The extension `.git` is mandatory in the URL
    # Not https://github.com/user/argocd but https://github.com/user/argocd.git
    url: ''
    # Basic Auth
    username: ''
    password: ''
  # WebHook auth
  # https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/
  webhook:
    # The service (github, gitlab, gogs, bitbucket, azuredevops)
    service: 'github'
    secret: ''
    username: ''
    password: ''
    uuid: ''
# ArgoCd Configuration
conf:
  # Control the `--kubectl-parallelism-limit` parameters of [argocd-application-controller](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-application-controller/)
  # Number of allowed concurrent kubectl fork/execs. Any value less the 1 means no limit. (default 20)
  # We change the default to avoid CPU spike: https://github.com/argoproj/argo-cd/discussions/6964#discussioncomment-1164100
  controller_kubectl_parallelism_limit: 1
  # Control the `reposerver.parallelism.limit` parameter
  # [argocd-repo-server](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-repo-server/)
  # Limit on number of concurrent manifests generate requests (manifest tool invocations)
  # We change the default to avoid CPU spike: https://github.com/argoproj/argo-cd/discussions/6964#discussioncomment-1164100
  reposerver_parallelism_limit: 1
  # Control the `--metrics-cache-expiration duration` parameter (disabled  by default. e.g. 24h0m0s) of [argocd-application-controller](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-application-controller/)
  # As recommended here: https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#application-controller-metrics
  controller_metrics_cache_expiration: '24h0m0s'


secret:
  # Kind of secret generated
  kind: 'Secret'

# Internal
# Used to not output manifest from cross dependency in this charts
kube_x_internal:
  dont_install_cross_dependency: false

