# Enabled or not
# not a string, don't quote
enabled: false
# The namespace
namespace: 'dex'

# The public hostname
# (Required as you need a callback)
hostname: ''

# connectors
connectors:
  # https://dexidp.io/docs/connectors/github/
  github:
    client_id: ''
    client_secret: ''
    # List of orgs that may connect
    orgs: []

# Client
clients:
  traefik_forward_auth:
    client_id: 'traefik-forward-auth'
    secret: '' # shared secret mandatory

# Internal don't change
kubee_internal:
  install_cross_dependency: false

# Dex Chart Values
# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  configSecret:
    create: false # we do it
    name: "dex-kubee-config"
  image:
    # https://github.com/dexidp/dex/releases
    tag: 'v2.41.1'
  https:
    # False because it enable it with only one flag via command line and it conflicts with the configuration
    enabled: true
  # Deployment volumes
  # as seen here: https://github.com/dexidp/dex/blob/a6dfa5ca9f9e1c819a846bd667c3c357da5252ac/examples/k8s/dex.yaml#L34
  volumeMounts:
    - name: tls
      mountPath: /etc/dex/tls
  volumes:
    - name: tls
      secret:
        secretName: dex-kubee-tls
  serviceMonitor:
    enabled: true
  networkPolicy:
    enabled: true


