# Enabled or not
# not a string, don't quote
enabled: false
# The namespace
namespace: 'dex'

# The public hostname
# (Required as you need a callback)
hostname: ''

# connectors
# https://dexidp.io/docs/connectors
connectors: []

# Clients
# https://dexidp.io/docs/guides/using-dex/#configuring-your-app
clients:
  # Traefik Forward Auth
  traefik_forward_auth:
    # The oidc client id
    client_id: 'traefik-forward-auth'
    # The oidc client secret (used to exchange the code between traefik_forward_auth and dex)
    secret: ''
    # app_domains: the app domains (without https) of the protected apps
    # This value is only mandatory when traefik_forward_auth has no hostname
    # ie when traefik_forward_auth is not in auth-host mode, but in overlay mode
    # https://github.com/thomseddon/traefik-forward-auth#auth-host-mode
    # In this case, all overloaded web app should be listed as authorized redirect uris
    app_domains: []
  # Other client
  # https://dexidp.io/docs/guides/using-dex/#configuring-your-app
  others: []

# Internal don't change
kubee_internal:
  install_cross_dependency: false

# Dex Chart Values
# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  configSecret:
    create: false # we do it
    name: "dex-kubee-config"
  image:
    # https://github.com/dexidp/dex/releases
    tag: 'v2.41.1'
  https:
    # False because it enable it with only one flag via command line and it conflicts with the configuration
    enabled: true
  # Deployment volumes
  # as seen here: https://github.com/dexidp/dex/blob/a6dfa5ca9f9e1c819a846bd667c3c357da5252ac/examples/k8s/dex.yaml#L34
  volumeMounts:
    - name: tls
      mountPath: /etc/dex/tls
  volumes:
    - name: tls
      secret:
        secretName: dex-kubee-tls
  serviceMonitor:
    enabled: true
  networkPolicy:
    enabled: true


