# Enabled or not
# not a string, don't quote
enabled: false
# The namespace
# Used also for all auth clients such as auth proxy
namespace: 'auth'

# The public hostname
# (Required as you need a callback)
hostname: ''

# connectors
# https://dexidp.io/docs/connectors
connectors: []

# Clients
# https://dexidp.io/docs/guides/using-dex/#configuring-your-app
clients:
  # Kubernetes
  # The client id (ie token audience) accepted by Kubernetes Oidc for login
  kubernetes:
    # The client id
    # If changed, all kubee charts that depends on should be deployed again
    client_id: 'kubernetes'
  # Oauth2_proxy
  # For Traefik Forward Auth Middleware
  oauth2_proxy:
    # The oidc client id
    # If changed, all kubee charts that depends on should be deployed again
    client_id: 'oauth2-proxy'
    # The oidc client secret (used to exchange the code between oauth2-proxy and dex)
    # openssl rand -base64 32
    secret: ''
  # Kubectl (ie kubectl oidc-login)
  # Added if the secret is not empty
  kubectl:
    # The client id
    # If changed, all kubectl config should be modified
    # and all kubee charts that depends on should be deployed again
    client_id: 'kubectl'
    # The oidc client secret (used to exchange the code between kubectl and dex)
    # paopenssl rand -base64 32
    secret: ''

  # Other client
  # https://dexidp.io/docs/guides/using-dex/#configuring-your-app
  others: []

# Expiration settings
# https://dexidp.io/docs/configuration/tokens/#expiration-and-rotation-settings
# It's possible to specify units using only s, m and h suffixes.
# This configuration are used by Oauth proxy to set cookie expiration settings
expiration:
  # The access token lifetime
  # 24h is the [default](https://github.com/dexidp/dex/blob/65814bbd7746611a359408bb355fb4e12d6e2c14/config.yaml.dist#L89),
  # 10m is the [recommended doc setting](https://dexidp.io/docs/configuration/tokens/#expiration-and-rotation-settings)
  # 1m is the [recommended setting of Oauth proxy](https://oauth2-proxy.github.io/oauth2-proxy/configuration/session_storage)
  # You can set the real value with the exp field of the JWS token
  access_token_lifetime: "10m"
  # The refresh token lifetime, it forces users to reauthenticate
  # 3960h (165 days) is the [dex default](https://github.com/dexidp/dex/blob/65814bbd7746611a359408bb355fb4e12d6e2c14/config.yaml.dist#L89),
  # 168h (7 days) is the [default cookie_expire value](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview?_highlight=cookie_expire#cookie-options)
  # You can see the real value in the cookie lifetime of oauth
  refresh_token_lifetime: "168h"


# Dex Chart Values
# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
dex:
  configSecret:
    create: false # we do it
    name: "dex-kubee-config"
  image:
    # https://github.com/dexidp/dex/releases
    tag: 'v2.41.1'
  https:
    # False because it enable it with only one flag via command line and it conflicts with the configuration
    enabled: true
  # Deployment volumes
  # as seen here: https://github.com/dexidp/dex/blob/a6dfa5ca9f9e1c819a846bd667c3c357da5252ac/examples/k8s/dex.yaml#L34
  volumeMounts:
    - name: tls
      mountPath: /etc/dex/tls
  volumes:
    - name: tls
      secret:
        secretName: dex-kubee-tls
  serviceMonitor:
    enabled: true
  networkPolicy:
    enabled: true


# Internal don't change
kubee_internal:
  install_cross_dependency: false