apiVersion: v2
name: kubee-grafana
description: Kubee Grafana Chart
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v5.16.0" # Grafana Operator version, should be the same in grafana-crds
# Grafana Version, click on the icon help in the Grafana UI)

annotations:
  app.kubernetes.io/name: "grafana"
  artifacthub.io/operator: "true"
  chart.kubee/status: "stable"
  chart.kubee/kind: "app"
  chart.kubee/category: "monitoring"
  chart.kubee/engines: |
    - helm
  chart.chart.kubee/crds: |
    - name: kubee-grafana-crds
      version: 5.16.0
      repository: file://../grafana-crds


dependencies:
  # ie https://github.com/grafana/grafana-operator/pkgs/container/helm-charts%2Fgrafana-operator
  # https://github.com/grafana/grafana-operator/releases
  - name: grafana-operator
    version: "v5.16.0"
    repository: "oci://ghcr.io/grafana/helm-charts"
    #condition: xxx.enabled
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
  - name: kubee-cert-manager
    version: 0.0.1
    repository: file://../cert-manager
    alias: cert_manager
    condition: kubee_internal.install_cross_dependency
  - name: kubee-traefik
    version: 0.0.1
    repository: file://../traefik
    alias: traefik
    condition: kubee_internal.install_cross_dependency
