{{- if and (eq .Values.kube_x.alertmanager.enabled true ) (ne .Values.kube_x.alertmanager.hostname "") }}
# https://github.com/prometheus-operator/prometheus-operator/blob/main/example/user-guides/alerting/alertmanager-example-service.yaml
# https://prometheus-operator.dev/docs/platform/platform-guide/#exposing-the-alertmanager-service
# We don't use a node port, we use an ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Because Middleware is not namespace, we use the kube-system-traefik-dashboard-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-traefik-dashboard-auth@kubernetescrd
    {{- if ne (((.Values).kube_x).cert_manager).enabled false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kube_x.cert_manager.defaultIssuerName }}'
    {{- end }}
spec:
  rules:
    - host: {{ .Values.kube_x.alertmanager.hostname }}
      http:
        paths:
          - backend:
              service:
                name: alertmanager
                port:
                  number: 9093
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.kube_x.alertmanager.hostname }}
      secretName: alertmanager-cert
{{- end -}}