# Ref:
# https://www.tauceti.blog/posts/run-postfix-in-kubernetes/#daemonset
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: postfix
  namespace: mailserver
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postfix
    spec:
      serviceAccountName: postfix
      terminationGracePeriodSeconds: 30
      # Cause Postfix to listen on the hosts network and NOT on an internal Pod IP.
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: registry-domain-tld
      containers:
        - image: registry.domain.tld:5000/postfix:0.1
          name: postfix
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            periodSeconds: 60
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            # maps hostPort 25 into containerPort 25.
            - name: smtp
              containerPort: 25
              hostPort: 25
            - name: smtp-auth
              containerPort: 587
              hostPort: 587
          # As we need to bind Postfix to a port < 1024 we need this security settings.
          # Limits what system calls the container is allowed to execute.
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
                - NET_BIND_SERVICE
          volumeMounts:
            - name: config
              subPath: bodycheck
              mountPath: /etc/postfix/bodycheck
              readOnly: true
            - name: config
              subPath: headercheck
              mountPath: /etc/postfix/headercheck
              readOnly: true
            - name: config
              subPath: main.cf.tmpl
              mountPath: /etc/postfix/main.cf.tmpl
              readOnly: true
            - name: config
              subPath: vmailbox
              mountPath: /etc/postfix/vmailbox
              readOnly: true
            - name: aliases
              subPath: aliases
              mountPath: /etc/mail/aliases
              readOnly: true
            - name: certs
              subPath: tls.crt
              mountPath: /etc/postfix/certs/tls.crt
              readOnly: true
            - name: certs
              subPath: tls.key
              mountPath: /etc/postfix/certs/tls.key
              readOnly: true
            - name: dhparam
              subPath: dh512.pem
              mountPath: /etc/postfix/dh512.pem
              readOnly: true
            - name: dhparam
              subPath: dh2048.pem
              mountPath: /etc/postfix/dh2048.pem
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: postfix
        - name: aliases
          configMap:
            name: mail
        - name: certs
          secret:
            secretName: mail-domain-tld-cert
        - name: dhparam
          secret:
            secretName: dhparam