{{- if ne .Values.cluster.dns.cloudflare.api_token '' }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "external-dns-cloudflare-secret-name" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  api_token: {{ .Values.cluster.dns.cloudflare.api_token }}
  {{- end }}