kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postal-name-config-secret" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  apiKey: YOUR_API_KEY
  email: YOUR_CLOUDFLARE_EMAIL
