{{/* Sercice for the Monitoring of External DNS*/}}
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: {{.Values.namespace}}
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector: {{ include "kubee-pod-labels" . | nindent 4}}
  ports:
    - name: http
      {{- /* Port of the service */}}
      port: 7979
      {{- /* Port of the container */}}
      targetPort: 7979
      protocol: TCP
