{{- if gt (len .Values.provider.env) 0 }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "external-dns-provider-secret-name" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  {{- range .Values.provider.env }}
  {{.name}}: {{ .value | b64enc }}
  {{- end }}

{{- end }}