{{/*Monitoring of External DNS*/}}
{{- if eq .Values.prometheus.enabled true }}
{{ $ := mergeOverwrite $ (dict "component" "external-dns") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubee-name" .}}
  namespace: {{.Values.namespace}}
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
spec:
  jobLabel: {{ index .Chart.Annotations "app.kubernetes.io/name" }}
  namespaceSelector:
    matchNames:
      - {{.Values.namespace}}
  selector:
    matchLabels:
      {{ include "kubee-pod-labels" . | nindent 6}}
  endpoints:
    - targetPort: 7979
      path: /metrics
      interval: {{.Values.prometheus.scrape_interval}}
{{- end }}