apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list","watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "" ]
    resources: [ "services","endpoints" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "extensions","networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get","watch","list" ]
  {{- if .Values.traefik.enabled }}
  # https://kubernetes-sigs.github.io/external-dns/latest/docs/sources/traefik-proxy/#manifest-for-clusters-with-rbac-enabled
  - apiGroups: ["traefik.containo.us","traefik.io"]
    resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
    verbs: ["get","watch","list"]
  {{- end}}
  # To allow CRD as source: https://kubernetes-sigs.github.io/external-dns/latest/docs/contributing/crd-source/#rbac-configuration
  - apiGroups: [ "externaldns.k8s.io" ]
    resources: [ "dnsendpoints" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "externaldns.k8s.io" ]
    resources: [ "dnsendpoints/status" ]
    verbs: [ "*" ]
