apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: {{.Values.namespace}}
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector:
    labels: {{ include "kubee-pod-labels" . | nindent 6}}
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
