apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: keycloak
  type: ClusterIP
