{{/*https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp*/}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mailpit-{{.Values.traefik.entrypoints.smtps.name}}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - {{.Values.traefik.entrypoints.smtps.name}}
  routes:
    - match: HostSNI(`{{ required "mailpit hostname is required" .Values.hostname }}`)
      priority: 10
      {{- if and (eq .Values.enable_private_network_middleware true) ( gt (len .Values.traefik.auth.private_networks) 0 ) }}
      middlewares:
        - name: {{ .Values.traefik.middlewares.private_network.name }}
          namespace: {{ .Values.traefik.namespace }}
      {{- end }}
      services:
        - name: mailpit-smtp          # Kubernetes Service
          port: smtp                  # Kubernetes Service Port
          weight: 10
          # With the proxy proxyProtocol the termination happens at traefik
          # and no certificate is shown
          # proxyProtocol:
          #  version: 2
          tls: false # Should be false with a tls passthrough otherwise the termination happens on the traefik side
  tls:
    # Tls termination happens on the service/pods side
    passthrough: true