{{- if and (gt (len $.Values.issuers.public.dns01.cloudflare.dns_zones) 0) (eq .Values.issuers.public.dns01.cloudflare.api_token.kind "Secret") }}
{{ $ := mergeOverwrite $ (dict "component" "cloudflare") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "cert-manager-cloudflare-secret-name" . }}'
  namespace: '{{ include "cert-manager.namespace" (dict "Values" (index $.Values "cert-manager") "Release" $.Release ) }}'
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
  labels:
      {{- include "kubee-manifest-labels" $ | indent 4}}
data:
   {{ .Values.issuers.public.dns01.cloudflare.api_token.key }}: {{ required "The cloudflare api token is required" .Values.issuers.public.dns01.cloudflare.api_token.value | b64enc }}
{{- end}}
