# Install the PushGateway
# https://hub.docker.com/r/prom/pushgateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "kubee-pod-labels" . | nindent 6}}
  template:
    metadata:
      labels: {{ include "kubee-pod-labels" .| nindent 8}}
    spec:
      containers:
        - name: pushgateway
          image: 'prom/pushgateway:{{.Values.version}}'
          ports:
            - containerPort: 9091