apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels: {{ include "kubee-manifest-labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector: {{ include "kubee-pod-labels" . | nindent 6}}
  ports:
    - name: pushgateway
      port: 9091
      protocol: TCP
      targetPort: 9091