apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app.kubernetes.io/name: pushgateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pushgateway
  ports:
    - name: pushgateway
      port: 9091
      protocol: TCP
      targetPort: 9091