enabled: false

namespace: mail

hostname: &mailuHostname ''

domain: &mailuDomain ''

mailu:
  ## hostnames:
  ##   - mail.example.com
  ##   - imap.example.com
  hostnames:
    - *mailuHostname
  # Mail Domain
  domain: *mailuDomain
  # Initial Account
  initialAccount:
    enabled: true
    username: "{{ $.Values.cluster.auth.admin_user.username }}"
    password: "{{ $.Values.cluster.auth.admin_user.password }}"

  # Running on bare metal with k3s and klipper-lb
  # https://github.com/Mailu/helm-charts/tree/master/mailu#running-on-bare-metal-with-k3s-and-klipper-lb
  front.hostPort.enabled: false
  externalService.enabled: true
  externalService.type: LoadBalancer
  externalService.externalTrafficPolicy: Local


# Don't change, don't touch
# Used to not output template from cross dependency in Chart.yaml
kubee_internal:
  install_cross_dependency: false