version: '3'

tasks:
  # Generate the values.schema.json
  schema:
    cmds:
      # Traefik values.schema.json should not be generated, we filter
      - helm schema --helm-docs-compatibility-mode -k additionalProperties
  # Generate the docs
  docs:
    cmds:
      - helm-docs
  # Update the charts/ directory
  dep:
    cmds:
      - kubee helmet update-dependencies oauth2-proxy
  # Template out
  tpl:
    cmds:
      - kubee helmet template --out oauth2-proxy
  # Install
  play:
    cmds:
      - kubee helmet play oauth2-proxy
