# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false
# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'auth'
# -- The oauth-proxy [release version](https://github.com/oauth2-proxy/oauth2-proxy/releases)
version: "v7.8.1"
# @schema
# title: Hostname
# description: The public hostname
# required: true
# format: hostname
# minLength: 1
# @schema
# -- The public hostname
hostname: ''
# Auth
auth:
  # @schema
  # required: true
  # minLength: 16
  # @schema
  # -- Secret Mandatory: A random value used to sign cookies
  # It must be 16, 24, or 32 bytes to create an AES cipher
  # Example command: `dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 | tr -d -- '\n' | tr -- '+/' '-_' ; echo`
  # [Doc Reference](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#generating-a-cookie-secret)
  cookie_secret: ''
  # @schema
  # type: boolean
  # @schema
  # -- Add the domain of the hostname as cookie domain and while list domain
  use_domain_hostname: true
  # @schema
  # format: hostname
  # @schema
  # -- Possible domains of the cookie.
  # The longest domain matching the request's host is used (or the shortest cookie domain if there is no match).
  cookie_domains: []
  # @schema
  # title: Refresh interval before access token expiration
  # type: integer
  # required: true
  # @schema
  # -- The interval in minutes in which the refresh of the access token will happen before expiration (in minutes)
  # `120` is the default and not `1` because of this [issue](https://github.com/oauth2-proxy/oauth2-proxy/issues/1942#issuecomment-2700271002)
  token_refresh_interval: 120
  # @schema
  # format: hostname
  # @schema
  # -- Whitelist domains.
  # The allowed domains for redirection back to the original requested target
  whitelist_domains: []
  # @schema
  # format: hostname
  # @schema
  # -- Email Domains.
  # Only users with this domain will be let in.
  # Accepted value: `*` for all emails or a hostname `your.company.com`
  email_domains: [ '*' ]
  # @schema
  # format: email
  # @schema
  # -- Authenticated email address.
  # Only users with this email addresses will be let in
  # The admin email is already taken into account
  email_addresses: []


# Oauth proxy helm values
# https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml
# @ignored
oauth2-proxy:
  config:
    # We use our own secret
    # The secret name
    existingSecret: oauth2-proxy-config
    # We use our own config
    # the configmap name
    existingConfig: oauth2-proxy-config
  # To set the name of objects
  fullnameOverride: 'oauth2-proxy'
  # To set the name of labels
  nameOverride: 'oauth2-proxy'
  # Metrics
  metrics:
    # Enable Prometheus metrics endpoint
    enabled: true
    serviceMonitor:
      # We do it ourselves
      enabled: false
  # Authenticated email
  authenticatedEmailsFile:
    # Not generated by the oauth2_proxy Helm Chart but by our chart
    enabled: false
    # Defines how the email addresses file will be projected, via a configmap or secret
    persistence: configmap
    # template is the name of the configmap what contains the email user list
    # Be aware the value name in the extern config map in data needs to be named to "restricted_user_access" or to the
    # provided value in restrictedUserAccessKey field.
    template: "oauth2-proxy-authenticated-emails"
    # The configmap/secret key under which the list of email access is stored
    restrictedUserAccessKey: "authenticated-emails"
  # Local User
  htpasswdFile:
    enabled: false # Dex or the oidc is having a list of user
  # Tls
  # https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy#tls-configuration
  httpScheme: https
  # Args are in config map
  #extraArgs:
  #  tls-cert-file: /etc/oauth2-proxy/tls/cert.pem
  #  tls-key-file: /etc/oauth2-proxy/tls/cert.key
  extraVolumeMounts:
    - name: tls
      mountPath: /etc/oauth2-proxy/tls
  extraVolumes:
    - name: tls
      secret:
        secretName: oauth2-proxy-kubee-tls-ca

# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false