{{- if ne .Values.kube_x.vault.hostname "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: {{ .Values.kube_x.vault.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if ne (((.Values).kube_x).cert_manager).enabled false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kube_x.cert_manager.defaultIssuerName }}'
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: '{{ .Values.kube_x.vault.hostname }}'
      http:
        paths:
          - backend:
              service:
                name: 'vault'
                port:
                  number: 8200
            path: /
            pathType: Prefix
  {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
  tls:
    - hosts:
        - '{{ .Values.kube_x.vault.hostname }}'
      secretName: 'vault-cert'
  {{- end }}
{{- end -}}
