{{/*
Dex configuration

The document is in the example:
https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml

Config of dex is already a template, a Gomplate template
https://dexidp.io/docs/getting-started/#templated-configuration
The deployment has a checksum to verify that the content has not changed

Dex exclusively pulls configuration options from one config file.
* Getting Started: https://dexidp.io/docs/getting-started/#configuration
* Ref: https://dexidp.io/docs/configuration/

Example:
 * K8s: https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml#L68

Templating:
  * Doc: https://dexidp.io/docs/getting-started/#templated-configuration
  * uses: https://github.com/hairyhenderson/gomplate
*/}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.dex.configSecret.name }}
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  config.yaml: |
    # Public issuer URL
    # (Must match the one configured in traefik-forward-auth)
    # The base path of dex and the external name of the OpenID Connect service.
    # This is the canonical URL that all clients MUST use to refer to dex. If a
    # path is provided, dex's HTTP service will listen at a non-root URL.
    issuer: "https://{{ .Values.hostname }}"

    # Store session data in Kubernetes CRD objects
    # Storage: https://dexidp.io/docs/configuration/storage/
    # Kub Storage Ref: https://dexidp.io/docs/configuration/storage/#kubernetes-custom-resource-definitions-crds
    # Ref: https://dexidp.io/docs/configuration/storage/#configuration
    storage:
      type: kubernetes
      config:
        inCluster: true
    
    # https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml#L48C1-L48C40

    web:
      # Http Uncommented
      # Why? Helm deployment starts already the port HTTP 5556 from the command line
      #      Helm starts already the port 5556 from the command line
      #      You get 5556: bind: address already in use
      # http: 0.0.0.0:5556
      # https: 0.0.0.0:5554
      # Path of the cert in the container
      # Mounted via volume
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
      headers:
        X-Frame-Options: "DENY"
        X-Content-Type-Options: "nosniff"
        X-XSS-Protection: "1; mode=block"
        Content-Security-Policy: "default-src 'self'"
        Strict-Transport-Security: "max-age=31536000; includeSubDomains"
      clientRemoteIP:
        header: X-Forwarded-For
        trustedProxies:
{{ .Values.kubee.auth.trusted_proxies | toYaml | indent 10}}
    

    # Front end customization
    # Ref: https://dexidp.io/docs/guides/templates/
    # frontend:
    #   issuer: dex
    #   logoURL: theme/logo.png
    #   dir: web/
    #   theme: light
    
    # Here is where you would configure your authentication backend.
    # See https://github.com/dexidp/dex#connectors for a list of supported connectors.
    # https://dexidp.io/docs/connectors/github/
    connectors:
      {{- if ne .Values.connectors.github.client_secret ""}}
      - type: github
        id: github
        name: GitHub
        config:
          clientID: "{{ .Values.connectors.github.client_id }}"
          clientSecret: "{{ .Values.connectors.github.client_secret }}"
          redirectURI: "https://{{ required "The dex hostname is required for the callback" .Values.hostname }}/callback"
          # List of orgs that may connect
          orgs: {{ .Values.connectors.github.orgs }}
      {{- end }}

    # OAuth2 flow customization options
    # https://dexidp.io/docs/configuration/oauth2/
    oauth2:
      # By default, Dex will ask for approval to share data with application
      skipApprovalScreen: true

    # Client registration 
    staticClients:
      {{- if ne .Values.clients.traefik_forward_auth.secret ""}}
      # This is internal client config for traefik-forward-auth.
      - name: Traefik Forward Auth
        id: {{ .Values.clients.traefik_forward_auth.client_id }}
        # Shared Secret
        secret: {{ .Values.clients.traefik_forward_auth.secret }}
        redirectURIs:
          - 'https://{{ required "traefik_forward_auth.hostname is required" .Values.traefik_forward_auth.hostname }}/_oauth'
      {{- end }}

    # builtin connector (password stored in dex)
    # https://dexidp.io/docs/connectors/local/
    enablePasswordDB: true
    staticPasswords:
      - email: "{{.Values.kubee.auth.admin_user.email}}"
        # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
        # https://masterminds.github.io/sprig/crypto.html#bcrypt
        hash: "{{ bcrypt .Values.kubee.auth.admin_user.password }}"
        username: "{{.Values.kubee.auth.admin_user.username}}"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"