# A self-signed issuer, used to create the dex CA private key and cert (see below Certificate)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubee-name-prefix" . }}-self-signed
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
# Create the CA cert for the dex issuer.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubee-name-prefix" . }}-ca
  namespace: {{ .Values.namespace }}
spec:
  {{- /* Secret Name that will store the certificate (ie private key and certificate) */}}
  secretName: {{ include "kubee-name-prefix" . }}-ca
  commonName: "{{ (include "kubee-to-camel-case" .Release.Name)}} {{ include "kubee-to-camel-case"  (include "kubee-prefix" .)}} Ca"
  isCA: true
  duration: '87600h'  # ie 3650 days, default to 90 days
  issuerRef:
    kind: Issuer
    name: {{ include "kubee-name-prefix" . }}-self-signed
  usages:
    - any
---
# The dex issuer using the CA keypair (Ca certificate)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubee-name-prefix" . }}-ca
spec:
  ca:
    {{- /* Name of the certificate (ie private key and certificate) */}}
    secretName: {{ include "kubee-name-prefix" . }}-ca
