# Forward authentication to example.com
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-auth
spec:
  forwardAuth:
    address: https://dex.eraldy.com
    authResponseHeaders:
      - X-Forwarded-User
