apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: prometheus-new-relic-secret
spec:
  # The store from where
  secretStoreRef:
    name: vault-external-secret-store
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: prometheus-new-relic-secret # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Remote Write Credentials for Prometheus"
  # Mapping to local secret from remote secret
  data:
    - secretKey: prometheus-bearer # Prop Name in the secret
      remoteRef:
        key: new-relic # Name of the remote secret
        property: prometheus-bearer # Prop Name in the remote secret



