{{- if eq .Values.kube_x.prometheus.grafana_cloud.enabled true }}
{{- if eq .Values.kube_x.cluster.secret "ExternalSecret" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: {{ template "kube-x-prometheus-grafana-cloud-secret-name" }}
  labels:
    app.kubernetes.io/name: prometheus
spec:
  # The store from where
  secretStoreRef:
    name: {{ .Values.kube_x.external_secrets.store.name }}
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: {{ template "kube-x-prometheus-grafana-cloud-secret-name" }} # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Remote Write Credentials for Prometheus"
  # Mapping to local secret from remote secret
  data:
    - secretKey: prometheus-username # Prop Name in the secret
      remoteRef:
        key: grafana-cloud # Name of the remote secret
        property: prometheus-username # Prop Name in the remote secret
    - secretKey: prometheus-password # Prop Name in the secret
      remoteRef:
        key: grafana-cloud # Name of the remote secret
        property: prometheus-password # Prop Name in the remote secret
{{- end }}
{{- if (eq .Values.kube_x.cluster.secret "Secret") -}}
---
{{/*

Test:
helm template -s templates/prometheus-grafana-cloud-secret.yml \
  --set 'kube_x.cluster.email.smtp.host=smtp.gmail.com'  \
  . | yq

*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-x-prometheus-grafana-cloud-secret-name" }}
  labels:
    app.kubernetes.io/name: prometheus
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
  prometheus-username: {{ required "kube_x.prometheus.grafana_cloud.prometheus.username is required" .Values.kube_x.prometheus.grafana_cloud.prometheus.username | b64enc}}
  prometheus-password: {{ required "kube_x.prometheus.grafana_cloud.prometheus.password is required" .Values.kube_x.prometheus.grafana_cloud.prometheus.password | b64enc}}
{{- end -}}
{{- end -}}
