{{- /*
  # Defines an alert manager pod
  # For each Alertmanager resource, the Operator deploys a StatefulSet in the same namespace.
  # https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Alertmanager
  # Example: https://github.com/prometheus-operator/prometheus-operator/blob/main/example/user-guides/alerting/
  # equivalent to alertmanager.yml ?
*/}}
{{- if eq .Values.kube_x.prometheus.alertmanager.enabled true }}
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  {{- /*  # Number of replicas of each shard to deploy*/}}
  replicas: 1 # default
  {{- /*  # Service Account to run*/}}
  serviceAccountName: prometheus
  {{- /*
    # https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.AlertmanagerConfiguration
    #  alertmanagerConfiguration:
    #    name:
    #    global:
    #      resolveTimeout: 6m # 5m is the default
  */}}
  alertmanagerConfigSelector: {} # All config Objects
  alertmanagerConfigNamespaceSelector: {} # Select all namespace?
  {{- /*
    # By default, the alert manager had a matcher on the namespace
    # We disable this match ie
    # For a alertmanagerConfig in the namespace kube-prometheus, it would add to the route
    # matchers:
    #  - namespace="kube-prometheus"
    # See: https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.AlertmanagerConfigMatcherStrategy
  */}}
  alertmanagerConfigMatcherStrategy:
    type: None
  {{- /*  # The secret for the config (this is the default) */}}
  configSecret: alertmanager-alertmanager
  {{- /*
  # Loglevel
  # logLevel: debug
  # The external URL under which the Alert Manager service is externally available.
  */}}
  {{- if ne .Values.kube_x.prometheus.alertmanager.hostname "" }}
  externalUrl: 'https://{{ .Values.kube_x.prometheus.alertmanager.hostname }}'
  {{- end }}
{{- end -}}