#!/usr/bin/env bash

# This script update the version
# and crd from the upstream traefik sub-chart

source bashlib-error.sh
error::set_strict_mode
error::set_trap
source bashlib-echo.sh

# this works for executed script or sourced script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Get the Traefik chart
GRAFANA_CHART_VERSION=$(yq '.dependencies[] | select(.name == "grafana-operator") | .version' "$SCRIPT_DIR/../../apps/grafana/Chart.yaml" | tr -d '~' )
if [ "$GRAFANA_CHART_VERSION" == "" ]; then
  echo::err "Unable to retrieve the grafana chart version (the value was empty)"
  exit 1
fi
echo::info "Updating crds for the Grafana chart $GRAFANA_CHART_VERSION"

GRAFANA_VERSION="???"


echo::info "Updating crds Chart.yml with Grafana version: $GRAFANA_VERSION. Chart: $GRAFANA_CHART_VERSION"
yq ".appVersion = \"$GRAFANA_VERSION\"" -i Chart.yaml
yq ".version = \"$GRAFANA_CHART_VERSION\"" -i Chart.yaml

echo::info "Download the CRD of Grafana $GRAFANA_VERSION"
curl \
  -s \
  -o "templates/crds.yaml" \
  --fail \
  "https://github.com/grafana/grafana-operator/releases/download/$GRAFANA_CHART_VERSION/crds.yaml"

echo::success "The grafana chart was updated"