
# -- The [K3s version](https://github.com/k3s-io/k3s/releases)
version: 'v1.32.1+k3s1'

# @schema
# minLength: 32
# @schema
# -- The [k3s Token](https://docs.k3s.io/cli/token) (Mandatory). A random secret value that should not change ever because it's used to encrypt the data on disk.
# You can generate one with `openssl rand -base64 64 | tr -d '\n'`)
token: ''

# -- The [k3s Server Args](https://docs.k3s.io/cli/server)
# Example: `--kube-apiserver-arg="admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml"`
server_args: [ ]

# Hosts
hosts:
  # -- The Servers (Mandatory)
  # The number of hosts server must be odd to avoid split brain issues with etcd
  # The minimum number is:
  # - 1 for a single server cluster
  # - 3 for a [high availability cluster](https://docs.k3s.io/datastore/ha-embedded)
  servers: []
    # Example:
    # - fqdn: '' # The full qualified name (Mandatory) ie kubee-loc-server-01.example.com
    #   ip: ''   # The Ip Mandatory for an ssh/vps cluster
    #   name: '' # The name Mandatory for a docker cluster (ie the container name)
  # @ignored. Not yet in the template
  # The Agents. [Optional]
  agents: []
  # Configuration for all hosts
  all:
    # -- Connection
    connection:
      # User used for the connection
      # ie ansible_user
      # https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
      username: 'root'
      # Connection type
      # For ansible, ansible_connection. Example of values: ansible.builtin.ssh, community.docker.docker, ...
      # https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
      type: 'ssh'
    # -- [Optional] - An extra admin user added to the Host OS.
    # (ie in the wheel group, used when ssh was hardened by banning root connection).
    # The name and public key should not be empty.
    admin_user:
      # The name
      username: ''
      # The public key of the private key
      public_key: ''
