apiVersion: v1
kind: Service
# Service Patch to disable TLS verification for traefik
# Should be an annotation on the service object
# traefik.ingress.kubernetes.io/service.serverstransport: <namespace>-<ServersTransport name>@kubernetescrd
# https://doc.traefik.io/traefik/providers/overview/#provider-namespace
metadata:
  name: argocd-server
  "annotations":
    "traefik.ingress.kubernetes.io/service.serverstransport": "argocd-noverifytls@kubernetescrd"