apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postal-name-config-map" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  postal.yml: |-
{{.Values.conf_yaml |toYaml| indent 4}}
