apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postal-name-config-map" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  #postal.yml: toYaml .Values.config | b64enc | quote
  postal.yml: |-
    {{- range .Files.Lines "conf/postal.yaml" }}
{{ . | indent 4 }}
    {{- end}}
