apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postal-name-signing-key" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  signing.key: {{ .Values.signing_key | b64enc | quote }}
