kind: Secret
apiVersion: v1
metadata:
  name: {{ include "postal-name-postal-yml" . }}
  namespace: '{{.Values.namespace}}'
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  signing-key: {{ .Values.signing_key | b64enc | quote }}
  rails-secret-key: {{ .Values.signing_key | b64enc | quote }}
