{{ $ := mergeOverwrite $ (dict "component" "config") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubee-name" . }}
  labels:
    {{- include "kubee-manifest-labels" . | indent 4}}
data:
{{/*  postal.yml: {{ toYaml .Values.config | b64enc | quote }}*/}}
{{/*  signing.key: {{ .Values.signingKey | b64enc | quote }}*/}}
