# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'monitoring'


# Scrape of the kubelet (CPU and Memory Resources)
kubelet:
  # -- Enable kubelet monitoring
  enabled: true
  # -- Scrape interval.
  # Why 45s. Headlamp uses a CPU rate functon over 1 minutes
  # If the scrape interval is above 1m, there is no data returned
  scrape_interval: '45s'
  # -- Metrics Optimization. For memory and cost optimization, low level metrics are dropped
  # For api server, Buckets metrics are high cardinality metrics
  # that are not used in alerting but in debugging
  # and consume a lot of memory
  scrape_metrics_optimization: true

# Scrape of the api server
api_server:
  # -- Enable Api Server monitoring
  enabled: true
  # -- Scrape Interval (Normal default was 30s and 5s for sli)
  scrape_interval: '60s'
  # -- Metrics Optimization. For memory and cost optimization, low level metrics are dropped
  # For api server, Buckets metrics are high cardinality metrics
  # that are not used in alerting but in debugging
  # and consume a lot of memory
  scrape_metrics_optimization: true

# Scrape of the Core Dns server
core_dns:
  # -- Enable Core DNS monitoring
  enabled: true
  # -- Scrape Interval (normal default was 15s)
  scrape_interval: '30s'


kube_state_metrics:
  # -- Enable [Kube State Metrics Exporter](https://github.com/kubernetes/kube-state-metrics).
  # It exports apps/functional state metrics.
  enabled: true
  # -- [Kube State Metrics Version](https://github.com/kubernetes/kube-state-metrics/releases) without the `v`
  version: '2.14.0'
  # -- The scrape interval
  scrape_interval: '60s'
  # -- The max memory of the exporter
  memory: '50Mi'


node_exporter:
  # -- Enable [Node Exporter](https://github.com/prometheus/node_exporter)
  # It will gather server resources metrics
  enabled: true
  # -- [Node Exporter Version](https://github.com/prometheus/node_exporter/releases) without the `v`
  version: '1.8.2'
  # -- Scrape Interval (Default was 15s)
  scrape_interval: '45s'
  # -- Max memory of the exporter (On Kube Prometheus, it was set to 180Mi)
  memory: '50Mi'
  # -- Memory and cost optimization. Low levels metrics are dropped
  scrape_metrics_optimization: true


# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false
