{{ $component := "worker" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" (merge . (dict "component" $component)) }}
  labels:
    {{- include "kubee-manifest-labels" (merge . (dict "component" $component)) | indent 4}}
spec:
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 8}}
      annotations:
        checksum/secret: {{ include (print .Template.BasePath "/config/secret.yaml") . | sha256sum }}  # Checksum annotation
    spec:
      containers:
      - name: worker
        image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
        command: ["postal", "worker"]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
        volumeMounts:
        - name: config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: {{ include "postal-name-config" . }}