{{ $component := "worker" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubee-name" (merge . (dict "component" $component)) }}
  labels:
    {{- include "kubee-manifest-labels" (merge . (dict "component" $component)) | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 6}}
  template:
    metadata:
      labels:
        {{- include "kubee-pod-labels" (merge . (dict "component" $component)) | indent 8}}
      annotations:
        {{- include "postal-config-checksum-annotation" . | indent 8}}
    spec:
      containers:
      - name: worker
        image: "ghcr.io/postalserver/postal:{{ .Values.version }}"
        command: ["postal", "worker"]
        {{- /* resources: {{ toYaml .Values.resources | nindent 10 }} */}}
        env:
          - name: MAIN_DB_HOST
            value: '{{.Values.conf_kube.main_db.service_name}}.{{.Values.namespace}}.svc.cluster.local'
          - name: MAIN_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "postal-name-config-secret" . }}
                key: mariadb-password
          - name: MESSAGE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "postal-name-config-secret" . }}
                key: mariadb-password
          - name: RAILS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "postal-name-config-secret" . }}
                key: rails-secret-key
        ports:
          - name: metrics
            containerPort: {{ .Values.conf_yaml.worker.default_health_server_port }}
        volumeMounts:
          - name: config-map
            mountPath: /config/postal.yml
            subPath: postal.yml
            readOnly: true
          - name: smtp-tls
            mountPath: /config/certs
            readOnly: true
      volumes:
      - name: config-map
        configMap:
          name: {{ include "postal-name-config-map" . }}
      - name: smtp-tls
        secret:
          secretName: '{{ include "postal-name-tls" . }}'
      - name: config-secret
        secret:
          secretName: '{{ include "postal-name-config-secret" . }}'