{{- if ne .Values.prometheus.enabled false -}}

apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.name }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system
  ports:
  - port: 9100
    name: "metrics"
    targetPort: metrics
    protocol: TCP

{{- end }}