{{- if eq .Values.traefik_forward_auth.enabled true }}
# Forward authentication to example.com
# https://doc.traefik.io/traefik/middlewares/http/forwardauth/#configuration-examples
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{.Values.middlewares.forward_auth.name }}
  namespace: {{ x.Values.namespace }}
spec:
  forwardAuth:
    address: "http://traefik-forward-auth.{{ .Values.traefik_forward_auth.namespace }}.svc.cluster.local:4181"
    authResponseHeaders:
      - X-Forwarded-User
{{- end }}
