{{- if eq .Values.traefik_forward_auth.enabled true }}
# Forward authentication to example.com
# https://doc.traefik.io/traefik/middlewares/http/forwardauth/#configuration-examples
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{.Values.middlewares.forward_auth.name }}
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    {{- /* For info: Authentik supports forward auth https://docs.goauthentik.io/docs/add-secure-apps/providers/proxy/server_traefik*/}}
    address: "http://traefik-forward-auth.{{ .Values.traefik_forward_auth.namespace }}.svc.cluster.local:4181"
    authResponseHeaders:
      # The authenticated user is set in the X-Forwarded-User header
      # https://github.com/thomseddon/traefik-forward-auth#forwarded-headers
      - X-Forwarded-User
{{- end }}
