# The controller metrics to get health status
# https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#application-controller-metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  labels:
    release: prometheus-operator
    app.kubernetes.io/name: argocd-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
    - port: metrics
      relabelings:
        # Drop the discovery service label
        # We keep service to be able to get the kb by service
        - action: labeldrop
          regex: '(container|endpoint|job|namespace|pod)'
      metricRelabelings:
        # repo: We have only one repo
        # `dest_server: https://kubernetes.default.svc` - we have only one cluster
        # `dest_namespace` : the destination namespace of the app
        # autosync_enabled="true
        # instance="10.42.0.61:8082" of the service
        # namespace="argocd" for all apps ???
        # project="default" - we have only one project
        - action: labeldrop
          regex: '(repo|dest_server|dest_namespace|autosync_enabled|instance|project|namespace)'
