# Doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#traefik-v22
# Chart: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#ingress-configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
{{- if ne ( ((.Values.kube_x).argocd).hostname) "" -}}
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
    cert-manager.io/cluster-issuer: '{{ .Values.kube_x.cert_manager.defaultIssuerName }}'
    {{- end }}
    # Only from Github or our network
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.kube_x.traefik.namespace }}-{{ include "kube-x-traefik-github-hooks-allow-list-name" . }}@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: '{{ .Values.kube_x.argocd.hostname }}'
      http:
        paths:
          - backend:
              service:
                name: 'argocd-server'
                port:
                  number: 443
            path: /
            pathType: Prefix
  {{- if ne (((.Values.kube_x).cert_manager).enabled) false }}
  tls:
    - hosts:
        - '{{ .Values.kube_x.argocd.hostname }}'
      secretName: '{{ include "grafana-name" . }}'
  {{- end }}
{{- end -}}


