{{/*
  See definition here:
  https://github.com/argoproj/argo-cd/blob/b8508f29162b91a547ec94b25df8e1011c6576fb/docs/operator-manual/argocd-secret.yaml
*/}}
{{- if (eq .Values.kube_x.cluster.secret "ExternalSecret") -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: argocd-secret
  namespace: {{ .Values.kube_x.argocd.namespace }}
spec:
  # The store from where
  secretStoreRef:
    name: {{ .Values.kube_x.external_secrets.store.name }}
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: argocd-secret # Secret name in Kubernetes
    {{/*
     The secret is already created and contains secret
     It should not be created again???
     Be careful, argocd-secret is used by argocd to store its own secret
     See definition here: https://github.com/argoproj/argo-cd/blob/d3c850b8e7e67d1aa4c2deb6b77a4edbf4b7f261/docs/operator-manual/argocd-secret.yaml
     We merge it then
     */}}
    creationPolicy: 'Merge'
    template:
      data:
        webhook.{{ .Values.kube_x.argocd.git.service }}.secret: "{{ printf "{{ .webhook_secret }}" }}"
        {{/*
          bcrypt hash of the password (by default, randomly generated at install and stored in `argocd-initial-admin-secret`)
          # https://kostis-argo-cd.readthedocs.io/en/refresh-docs/getting_started/first_steps/#find-the-initial-password
        */}}
        admin.password: '{{ print "{{ print .admin_password | bcrypt }}" }}'
      metadata:
        annotations:
          description: "The WebHook Secret that permits to authenticate the GitHub Webhook"
  # Mapping to local secret from remote secret
  data:
    - secretKey: admin_password # Prop Name in the secret
      remoteRef:
        key: argocd # Name of the remote secret
        property: admin-password # Prop Name in the remote secret
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#2-configure-argo-cd-with-the-webhook-secret-optional
    - secretKey: webhook_secret # Prop Name in the secret
      remoteRef:
        key: argocd # Name of the remote secret
        property: webhook-secret # Prop Name in the remote secret
{{- else -}}
{{/*

Test:
helm template -s templates/argocd-secret.yml \
  --set 'kube_x.cluster.adminUser.password=welcome'  \
  . | yq

*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: 'argocd-secret'
  namespace: '{{ .Values.kube_x.argocd.namespace }}'
  annotations:
    description: "WebHook Secret and admin password"
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
  {{- /*
    WebHook
    https://argo-cd.readthedocs.io/en/latest/operator-manual/webhook/#2-configure-argo-cd-with-the-webhook-secret-optional
  */}}
  {{- if ne .Values.kube_x.argocd.git.webhook.secret "" }}
  webhook.{{ .Values.kube_x.argocd.git.webhook.service }}.secret: "{{ .Values.kube_x.argocd.git.webhook.secret | b64enc}}"
  {{- end }}
  {{- if ne .Values.kube_x.argocd.git.webhook.uuid "" }}
  webhook.{{ .Values.kube_x.argocd.git.webhook.service }}.uuid: "{{ .Values.kube_x.argocd.git.webhook.uuid | b64enc}}"
  {{- end}}
  {{- if ne .Values.kube_x.argocd.git.webhook.username "" }}
  webhook.{{ .Values.kube_x.argocd.git.webhook.service }}.username: "{{ .Values.kube_x.argocd.git.webhook.username | b64enc}}"
  webhook.{{ .Values.kube_x.argocd.git.webhook.service }}.username: "{{ required "kube_x.argocd.git.webhook.password is required" .Values.kube_x.argocd.git.webhook.password | b64enc}}"
  {{- end}}
  {{- /*
    Admin User
    User/Admin Management doc: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/

    Note: The admin username is `admin`. You can change it only with the `argocd cli`

    The password is a bcrypt hash of the password (by default, randomly generated at install and stored in `argocd-initial-admin-secret`)
    # https://kostis-argo-cd.readthedocs.io/en/refresh-docs/getting_started/first_steps/#find-the-initial-password
  */}}
  admin.password: '{{ printf "%s" (required "kube_x.cluster.adminUser.password is required" .Values.kube_x.cluster.adminUser.password) | bcrypt | b64enc }}'
{{- end -}}