# Email Notification User and Password
# https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/#getting-started
{{- if ne .Values.kube_x.cluster.email.smtp.host "" }}
{{- if (eq .Values.kube_x.cluster.secret "ExternalSecret") -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: {{ template "kube-x-argocd-notifications-secret-name" }}
  namespace: {{ .Values.kube_x.argocd.namespace }}
spec:
  # The store from where
  secretStoreRef:
    name: {{ .Values.kube_x.external_secrets.store.name }}
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: {{ template "kube-x-argocd-notifications-secret-name" }} # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Email Credentials for notifications"
  # Mapping to local secret from remote secret
  data:
    - secretKey: {{ template "kube-x-argocd-email-username-variable-name" }} # Prop Name in the kubernetes secret
      remoteRef:
        key: email # Name of the remote secret
        property: {{ template "kube-x-argocd-email-username-variable-name" }} # Prop Name in the remote secret
    - secretKey: {{ template "kube-x-argocd-email-password-variable-name" }} # Prop Name in the kubernetes secret
      remoteRef:
        key: email # Name of the remote secret
        property: {{ template "kube-x-argocd-email-password-variable-name" }} # Prop Name in the remote secret
{{/*

Test:
helm template -s templates/argocd-notifications-secret.yml \
  --set 'kube_x.cluster.email.smtp.host=smtp.gmail.com'  \
  --set 'kube_x.cluster.email.smtp.port=587'  \
  --set 'kube_x.cluster.email.smtp.username=nico'  \
  --set 'kube_x.cluster.email.smtp.password=welcome'  \
  --set 'kube_x.cluster.adminUser.email=foo@gmail.com' \
  . | yq

*/}}
{{- else -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-x-argocd-notifications-secret-name" }}
  namespace: {{ .Values.kube_x.argocd.namespace }}
{{- /*
 The values for all keys in the data field have to be base64-encoded strings.
 If the conversion to base64 string is not desirable, you can choose to specify the stringData field instead,
 which accepts arbitrary strings as values.
*/}}
data:
  {{ template "kube-x-argocd-email-username-variable-name" }}: {{ required ".Values.kube_x.cluster.email.smtp.username is required" .Values.kube_x.cluster.email.smtp.username }}
  {{ template "kube-x-argocd-email-password-variable-name" }}: {{ required ".Values.kube_x.cluster.email.smtp.password is required" .Values.kube_x.cluster.email.smtp.password }}
{{- end -}}
{{- end -}}