{{- /*
  Command line configuration
  Command line argument
  https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cmd-params-cm-yaml/
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
{{/*  namespace: '{{ .Values.kube_x.argocd.namespace }}'*/}}
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    kustomize.config.k8s.io/behavior: merge
data:
  # Prometheus's metrics cache expiration (disabled  by default. e.g. 24h0m0s)
  # As recommended here: https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#application-controller-metrics
  controller.metrics.cache.expiration: '24h0m0s'
