# Email Notification User and Password
# https://argo-cd.readthedocs.io/en/stable/operator-manual/notifications/#getting-started
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: argocd-notifications-secret
spec:
  # The store from where
  secretStoreRef:
    name: vault-external-secret-store
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: argocd-notifications-secret # Secret name in Kubernetes
    template:
      metadata:
        annotations:
          description: "The Email Credentials for notifications"
  # Mapping to local secret from remote secret
  data:
    - secretKey: email-username # Prop Name in the kubernetes secret
      remoteRef:
        key: gmail # Name of the remote secret
        property: smtp-user # Prop Name in the remote secret
    - secretKey: email-password # Prop Name in the kubernetes secret
      remoteRef:
        key: gmail # Name of the remote secret
        property: smtp-password # Prop Name in the remote secret


