# Be careful, argocd-secret is used by argocd to store its own secret
# See definition here: https://github.com/argoproj/argo-cd/blob/d3c850b8e7e67d1aa4c2deb6b77a4edbf4b7f261/docs/operator-manual/argocd-secret.yaml
# We merge it then
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # A unique name in the namespace
  name: argocd-secret
spec:
  # The store from where
  secretStoreRef:
    name: vault-external-secret-store
    kind: ClusterSecretStore
  # The target define the secret created
  # and may be pre-processed via template
  target:
    name: argocd-secret # Secret name in Kubernetes
    # The secret is already created and contains secret
    # It should not be created again
    # see definition here: https://github.com/argoproj/argo-cd/blob/d3c850b8e7e67d1aa4c2deb6b77a4edbf4b7f261/docs/operator-manual/argocd-secret.yaml
    creationPolicy: 'Merge'
    template:
      data:
        webhook.github.secret: "{{ .github_webhook_token }}"
        # bcrypt hash of the password (by default, randomly generated at install and stored in `argocd-initial-admin-secret`)
        # https://kostis-argo-cd.readthedocs.io/en/refresh-docs/getting_started/first_steps/#find-the-initial-password
        admin.password: '{{ printf "%s" .admin_password | bcrypt }}'
      metadata:
        annotations:
          description: "The WebHook Secret that permits to authenticate the GitHub Webhook"
  # Mapping to local secret from remote secret
  data:
    - secretKey: admin_password # Prop Name in the secret
      remoteRef:
        key: argocd # Name of the remote secret
        property: admin-password # Prop Name in the remote secret
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#2-configure-argo-cd-with-the-webhook-secret-optional
    - secretKey: github_webhook_token # Prop Name in the secret
      remoteRef:
        key: argocd # Name of the remote secret
        property: github-webhook-token # Prop Name in the remote secret
    # gitlab webhook secret
    # webhook.gitlab.secret: shhhh! it's a GitLab secret
    # bitbucket webhook secret
    # webhook.bitbucket.uuid: your-bitbucket-uuid
    # bitbucket server webhook secret
    # webhook.bitbucketserver.secret: shhhh! it's a Bitbucket server secret
    # gogs server webhook secret
    # webhook.gogs.secret: shhhh! it's a gogs server secret
    # azuredevops username and password
    # webhook.azuredevops.username: admin
    # webhook.azuredevops.password: secret-password

