apiVersion: v2
name: kubee-argocd
description: Kubee ArgoCd Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.14.4" # The version of argocd (in kustomization.yml url)

annotations:
  chart.kubee/status: "stable"
  chart.kubee/kind: "app"
  chart.kubee/category: "ci-cd"
  chart.kubee/engines: |
    - helm
    - kustomize

# https://github.com/external-secrets/external-secrets/releases
dependencies:
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  # For the ingress
  - name: kubee-cert-manager
    version: 0.0.1
    repository: file://../cert-manager
    alias: cert_manager
    condition: kubee_internal.install_cross_dependency
  # For the dashboard
  - name: kubee-grafana
    version: 0.0.1
    repository: file://../grafana
    alias: grafana
    condition: kubee_internal.install_cross_dependency
  # For the scrape
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
  # For CI
  - name: kubee-external-secrets
    version: 0.0.1
    repository: file://../external-secrets
    alias: external_secrets
    condition: kubee_internal.install_cross_dependency
  - name: kubee-traefik
    version: 0.0.1
    repository: file://../traefik
    alias: traefik
    condition: kubee_internal.install_cross_dependency

