# Enable or disable alert manager
# Not a string, a boolean so no quote
enabled: false
# version
# https://github.com/prometheus/alertmanager/releases
version: "v0.28.0"
# The installation namespace
# The same value as kube-prometheus
namespace: 'monitoring'
# Instance name
# The operator uses it to create unique alertmanager
# It's also a Kube-Prometheus mandatory variable
name: 'kube-x'
# hostname (install an ingress if not empty)
hostname: ''
# Opsgenie integration to send alert
# Enabled if the api key is not empty
opsgenie:
  api_key: ''
# Memory
resources:
  memory: '50Mi'

# Secret
secret:
  # The kind of Secret manifest created
  # Valid values are:
  # `Secret`: A Kubernetes Secret manifest is created, the values are passed in the values.yaml with environment variables substitution
  # `ExternalSecret`: A ExternalSecret Manifest is created that retrieves the value in a store (External Secret should be installed).
  #                   Used for GitOps pulling such as in ArgoCd where the git repository is pulled and applied.
  kind: 'Secret'


# Internal, don't change
# Used to not output manifest from cross helm dependency
kube_x_internal:
  install_cross_dependency: false