{{- if ne .Values.cluster.distriution "k3s"}}
{{ fail "Cluster is not k3s, sotrage class is unknown/unimplemented" }}
{{- end}}
{{ $ := mergeOverwrite $ (dict "component" "mariadb") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postal-mariadb-pvc-local-kubee
  labels:
      {{- include "kubee-manifest-labels" . | indent 4}}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  # https://docs.k3s.io/storage#setting-up-the-local-storage-provider
  storageClassName: local-path
  resources:
    requests:
      storage: {{.Values.conf_kube.main_db.volume_storage_size}}
