{{- if ne .Values.cluster.distriution "k3s"}}
{{ fail "Cluster is not k3s, sotrage class is unknown/unimplemented" }}
{{- end}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postal-mariadb-pvc-local-kubee
spec:
  accessModes:
    - ReadWriteOnce
  # https://docs.k3s.io/storage#setting-up-the-local-storage-provider
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi # minimum 2 times the repo of 300Mb
