apiVersion: v2
name: kubee-blackbox-exporter
description: Kubee BlackBox Exporter Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1 # The version of the chart (doesn't matter and can stay the same)

# This is the version number of the application being deployed.
# The version of blackbox operator
appVersion: "0.28.0"

keywords:
  - monitoring
  - prometheus
  - kubee

annotations:
  app.kubernetes.io/name: "blackbox"
  chart.kubee/status: "stable"
  chart.kubee/lead: "Check your services with HTTP, DNS, TCP, ..."
  chart.kubee/kind: "app"
  chart.kubee/category: "monitoring"
  chart.kubee/engines: |
    - jsonnet
  # Depend on the probe CRD of prometheus operator
  # https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Probe
  chart.kubee/crds: |
    - name: kubee-prometheus-crds
      version: 0.79.2
      repository: file://../prometheus-crds

dependencies:
  - name: kubee-cluster
    version: 0.0.1
    repository: file://../cluster
    alias: cluster
  # For the ingress
  - name: kubee-cert-manager
    version: 0.0.1
    repository: file://../cert-manager
    alias: cert_manager
    condition: kubee_internal.install_cross_dependency
  # For the dashboard
  - name: kubee-grafana
    version: 0.0.1
    repository: file://../grafana
    alias: grafana
    condition: kubee_internal.install_cross_dependency
  # For service monitor interval
  - name: kubee-prometheus
    version: 0.0.1
    repository: file://../prometheus
    alias: prometheus
    condition: kubee_internal.install_cross_dependency
  # For ingress auth
  - name: kubee-traefik
    version: 0.0.1
    repository: file://../traefik
    alias: traefik
    condition: kubee_internal.install_cross_dependency
