
# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: monitoring

# -- Blackbox exporter [version](https://github.com/prometheus/blackbox_exporter/releases)
#
version: 0.26.0

# -- The period in minutes to consider for the probe to fail
# Why 2m? If we probe every minute, the alert seems to not fire if the interval is 1m
probe_failed_interval: '2m'

# used by kube-prometheus to reload
reloader:
  # [Version](https://github.com/jimmidyson/configmap-reload/tags)
  version: 0.14.0