# @schema
# title: Enabled
# type: boolean
# required: true
# default: false
# @schema
# -- Boolean to indicate that this chart is or will be installed in the cluster
enabled: false

# @schema
# title: Namespace
# description: The installation namespace
# required: true
# minLength: 1
# @schema
# -- The installation namespace
namespace: 'mail'

# @schema
# title: Hostname
# description: The public hostname
# required: true
# minLength: 1
# format: hostname
# @schema
# -- The public hostname
hostname: ''

# @schema
# required: true
# minLength: 1
# format: hostname
# @schema
# -- The mail domain
domain: ''

# @ignored
mailu:
  ## hostnames:
  ##   - mail.example.com
  ##   - imap.example.com
  hostnames:
    - '{{ .Values.hostname }}'
  # Mail Domain
  domain: '{{ .Values.domain }}'
  # Initial Account
  initialAccount:
    enabled: true
    username: "{{ .Values.cluster.auth.admin_user.username }}"
    password: "{{ .Values.cluster.auth.admin_user.password }}"

  # Running on bare metal with k3s and klipper-lb
  # https://github.com/Mailu/helm-charts/tree/master/mailu#running-on-bare-metal-with-k3s-and-klipper-lb
  front:
    hostPort:
      enabled: false
    externalService:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local



# -- @ignored Internal Kubee constant
kubee_internal:
  # @schema
  # const: false
  # @schema
  # Constant used to not output template from kubee cross dependency in Chart.yaml
  # Don't change, don't touch
  install_cross_dependency: false
